### ISSUE TITLE
Support uploading icons for custom apps

### ISSUE THREAD

**Issue by tomerh2001** [truenas/apps#1003]
Currently, when you create a custom application (using either the GUI or the YAML) it looks like this:
<img width="277" alt="image" src="https://github.com/user-attachments/assets/77c0cefa-bd63-476d-972b-bf4f3ca0d0a3">

It would be nice if there would be a configuration option to upload the icon.

Bonus points if you guys use something like [this](https://github.com/walkxcode/dashboard-icons) and allow the user to just input `traefik.png` in addition to uploading an image.

**Comment by stavros-k** [comment]
This is not something that can be solved from apps side.
I'd suggest opening a feature request at forums 
https://forums.truenas.com/c/features/12

Thanks
