### ISSUE TITLE
Wordpress app on Truenas Electric Eel port 30040 not disconnecting when app deleted.

### ISSUE THREAD

**Issue by trev458** [truenas/apps#1034]
Not an expert so bear with me.  Deployed the wordpress app in truenas with default settings.  Running ok.  Went to cloudflare zero tunnel and added a cloudflare tunnel. This is showing healthy.  Added public host name with the url  going to port 30040.  Couldn't get it to open the website.  Decided to delete app on truenas after some time playing around with it.  Run wordpress through the truenas portainer app.  Changed the cloudflare tunnel public hostname to the new port setting.  Tried opening web site and timed out with error

The connection has timed out

An error occurred during a connection to xxxxxxxxxxxxxxxx.com.au:30040.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

I have another domain running only on portainer and this opens up ok.
Previous to this issue I had both domains running on portainer app from truenas and using the cloudflared app to run the the tunnels and they were working ok.  I thought I would try the wordpress app on truenas and thats when the trouble started.

How do I go about clearing the port 30040 from the domain name / url?  

At this stage no port change done in zero tunnel has an effect.  It still tries to go to port 30040
Any help would be much appricated.

**Comment by stavros-k** [comment]
I'm not sure where you want to remove the port from.
If an app is deleted or stopped, the port is freed on the system.

If its something with wordpress settings, you have to use the wordpress admin to change site url or however it is called.

**Comment by trev458** [comment]
For some reason the same url is being directed to the default wordpress port 30040 on Truenas.
I would have thought this would have cleared when deleting the Wordpress app on Truenas.  I have created a new VM in proxmox and installed Truenas with portainer as per previous install. Loaded both wordpress with the same two domains and running through cloudflared tunnel and still end up with the same problem.  The same domain faults, and the other works ok.  It doesn't matter what port I configure in the tunnel and wordpress, it will still go to the default wordpress app port 30040
There are no docs for setting up the wordpress app on truenas electric eel, so am in the dark with that.  Not sure if there is a bug in the app.

**Comment by stavros-k** [comment]
Maybe this is what you need?
https://www.wpbeginner.com/wp-tutorials/how-to-change-your-wordpress-site-urls-step-by-step/

I'm still not sure where/what is the issue. Maybe share some screenshots?
