### ISSUE TITLE
nextcloud postgres upgrade needed

### ISSUE THREAD

**Issue by strich3** [truenas/apps#1058]
When I'm trying to use memories it always says this:

![image](https://github.com/user-attachments/assets/876d2592-d4d4-4c0c-9faf-db3498899cea)

When I execute the command it doesn't work:

![image](https://github.com/user-attachments/assets/5521753b-e10e-4370-a108-4fbba8c7df5f)

This error comes up, because memories apparently needs the postgres version 14 at minimum. (https://github.com/pulsejet/memories/issues/1106)
Any way to get this thing updated?

**Comment by stavros-k** [comment]
duplicate of https://github.com/truenas/apps/issues/342
