### ISSUE TITLE
Jellyfin Host Network option

### ISSUE THREAD

**Issue by wlj-iii** [truenas/apps#1075]
When editing settings from Apps Dashboard, if Host Network is selected, the option to select a port disappears. Navigating to the app using the Web UI button defaults to port 8096, even when port is changed in Jellyfin interface. TrueNAS stops receiving updates from the app if port is changed in Jellyfin.

**Comment by stavros-k** [comment]
Jellyfin does not have an option to change the internal port of the container from env variable or a cli flag.

So if you use host network it will listen to 8096 (or the port you set inside the jellyfin webui).
