### ISSUE TITLE
Gitea ssh URLs incorrect after migrating to Electric Eel

### ISSUE THREAD

**Issue by aroskuski** [truenas/apps#1093]
Before upgrading TrueNAS to Electric Eel, gitea would generate ssh URLs like this:
```
ssh://git@truenas.local:30009/<user>/<repo>.git
```
Afterwards, it generates ssh URLs like this:
```
git@truenas.local:<user>/<repo>.git
```

The ssh port info seems to have gotten lost somehow, and the newly generated URLs don't work as a result.  The previous format does still seem to actually work for connecting to the repos, so it seems like the URL generation is just configured incorrectly.

**Comment by stavros-k** [comment]
Can you share the app config please? 
Mainly the network section.

From a quick look the generated docker template matches with what equivalent chart would generate.

**Comment by aroskuski** [comment]
![image](https://github.com/user-attachments/assets/4b9726ea-77ba-4d3a-9721-19465e0835e3)

Hopefully this should be enough.  I haven't edited this at all since updating TrueNAS.

**Comment by stavros-k** [comment]
Can you check inside the container, the file `/data/gitea/conf/app.ini`
Does it have on both `SSH_PORT` and `SSH_LISTEN_PORT` the value `30009` ?

**Comment by aroskuski** [comment]
I couldn't find the file at that exact path, but based on the site administration section of the gitea UI, it seems to be present at `/etc/gitea/app.ini`

Here are the two relevant lines:
```ini
SSH_PORT = None
SSH_LISTEN_PORT = 30009
```

**Comment by stavros-k** [comment]
I see, found the issue.
Thanks
