### ISSUE TITLE
wg-easy: since 1.1.x the "Web UI" buttond doesn't work in TrueNAS, also ports don't show in UI.

### ISSUE THREAD

**Issue by kraptor** [truenas/apps#1144]
It seems the ports are messed up, and TrueNAS doesnt' map them correctly. The TrueNAS button for WebUI redirects to port 8006 instead, which fails to load (obviously).

Unexpectedly, the correct (default) port is correcltly exposed (:30058), but the it doesn't show up correctly in the exposed/mapped ports:
![image](https://github.com/user-attachments/assets/c0cd5068-5e54-468e-a4c5-a0cc010f5a6c)

**Comment by stavros-k** [comment]
Fix for button is up.
Regarding the port section, I dont think you will see ports there if Host network is enabled.

You can verify that no ports are listed by docker itself. (Which is were the data is pulled)

```sh
docker container inspect ix-wg-easy-wg-easy-1
```

If name does not match a container, you can find the container name by 

```sh
docker ps
```
