### ISSUE TITLE
App Request: Nextcloud All In One

### ISSUE THREAD

**Issue by NikoKS** [truenas/apps#1148]
Since Truenas is using docker now, it should be possible to run Nextcloud AIO version. This should simplify a lot of deployment hassle for people wanting full featured Nextcloud.

Link: https://github.com/nextcloud/all-in-one

Discussion on the topic: https://github.com/nextcloud/all-in-one/discussions/5506

**Comment by stavros-k** [comment]
Duplicate of #450
