### ISSUE TITLE
nextcloud:memories - Database triggers not set up; trigger compatibility mode in use.

### ISSUE THREAD

**Issue by ct85msi** [truenas/apps#1153]
When I install Memories plugin, in "Administration => Memories" I have this warning "Database triggers not set up; trigger compatibility mode in use."
See the documentation for information on how to resolve this. [External Link](https://memories.gallery/troubleshooting/#trigger-compatibility-mode)" 

I used occ maintenance:repair and I get: 

`     - WARNING: Failed to create filecache trigger (compatibility mode will be used): An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "TRIGGER"
LINE 1: CREATE OR REPLACE TRIGGER memories_fcu_trg
`

From my research, it seems the container needs Postgresql v14 for Memories to be able tu use it`s full performance.

TrueNAS 24.10.X

Thanks in advance,

Sorin

**Comment by stavros-k** [comment]
Hello, 

It needs Postgres >= 15
https://github.com/pulsejet/memories/blob/master/docs/install.md#requirements

<img width="1489" alt="image" src="https://github.com/user-attachments/assets/c1de9f4d-a184-4698-a4c7-f900a95bc1d5">

**Comment by ct85msi** [comment]
Thank you, I omitted the option for choosing the postgress version.
