### ISSUE TITLE
'Gaseous Server' needs additional steps, not mentioned during the installation.

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/apps#1165]
As the title suggests, the app needs additional steps that are not mentioned during the installation.

As it is now, after installing Gaseous Server the system will not recognise roms from certain console systems. In my personal experience, roms from the NES and SNES were not recognised and would be unusable. For this I made an issue at the Gaseous-Server Github (https://github.com/gaseous-project/gaseous-server/issues/465#issue-2734056275) for which the solution was provided, which I am relaying here.

After installing Gaseous Server, two additional steps are needed: 

1. The user needs to download a `.zip` file containing signatures (`.dat` files)from https://www.tosecdev.org/downloads, extract the contents of the `TOSEC` folder in said `.zip` file and place those files in the `TOSEC` folder in the `Signatures` folder for Gaseous Server. On TrueNAS Scale, this would be `/mnt/.ix-apps/app_mounts/gaseous-server/data/Data/Signatures/TOSEC/` which is mounted as `/root/.gaseous-server/Data/Signatures/TOSEC/` inside the container; Assuming the user chose to use an iXVolume ofcourse.
2. The signatures need to be imported. Here the user has 2 options:
- In the Gaseous Server webUI, go to **settings -> System** and start the **Signature import** task.
- Wait up to 60 minutes for the task to start automatically.

Please update the installer's notes to include these 2 steps, as they are required for the app to function properly.

**Comment by stavros-k** [comment]
A link to documentation is added here
https://github.com/truenas/apps/pull/1180
