### ISSUE TITLE
AdGuard Home HTTPS is not working (ix-dev/community)

### ISSUE THREAD

**Issue by sawden** [truenas/apps#1188]
**Details**
**Version:** TrueNAS SCALE ElectricEel 24.10
**App Version:** v0.107.55

It is currently not possible to use HTTPS in the AdGuard Home app. 
Enabling the "Use HTTPS Probe" option causes the app to get stuck in the "deploying" status. 

Upon reviewing the source code, it appears that the checkbox only changes the healthcheck URL from HTTP to HTTPS ([see here](https://github.com/truenas/apps/blob/dc35677d81b719ac21a850edc4d7d1a6ec6b2a62/ix-dev/community/adguard-home/templates/docker-compose.yaml#L4)).

**Steps to reproduce**
1. Enable the "Use HTTPS Probe" option in the AdGuard Home configuration.
2. Observe that the app gets stuck in the "deploying" state.

Another user has the same problem, describing it: [here in the Forum](https://forums.truenas.com/t/getting-use-https-probe-to-work-with-adguard-home/24659).

**Comment by stavros-k** [comment]
Hello, yes this checkbox does exactly what it says, Uses https probe and nothing else

<img width="582" alt="image" src="https://github.com/user-attachments/assets/016ca97f-c47c-4c74-866d-c425145c0181" />

If you find a way to configure https via environment variable or a cli flag for adguard home, feel free to let me know.
But last time I checked there wasn't a way to do that, but we exposed this checkbox for people that wanted to manually set this up from the webui.

Thanks
