### ISSUE TITLE
DDNS-Updater - Allow configuring the container's DNS address

### ISSUE THREAD

**Issue by guiweber** [truenas/apps#1201]
At the moment DDNS-Updater inherits the system's (TrueNAS) DNS configuration.

In some cases, this can prevent DDNS-Updater to DNS resolve domains and check if their IP need to be updated. It would thus be beneficial to allow configuring a different DNS address (i.e. a DNS field in the network section of the app configuration panel), which would be the equivalent of launching the container with the dns option: `docker run --dns XX.XX.XX.XX`

Here is one example where using the default DNS cause issues: Let's say you are running a publicly accessible service (myservice.mydomain.com) on your TrueNas, behind a reverse proxy, as well as a local DNS server. The TrueNas system is configured to use the local DNS server, and DDNS-Updater is configured to update myservice.mydomain.com. If the local DNS server has a Dnsmasq entry for myservice.mydomain.com pointing to the LAN address of the TrueNas system (to reduce latency and maximize throughput when services are accessed from the local network), DDNS-updater will not be able to DNS resolve the real address for myservice.mydomain.com.

Also, I noticed that using an external DNS server instead of my local DNS (pi-Hole) prevents https://github.com/truenas/apps/issues/751

**Comment by stavros-k** [comment]
I'm pretty sure that ddns-updater will use a public provider to resolve DNS.
You can also select which one to use on the `Public IP DNS Providers` field.

Even if dns field (equivalent to --dns) is exposed in the UI, I'm still not sure it will make a difference,
cause your dnsmaq rule will still apply there (assuming you targeting port 53 for the rule).
For example I use such rule on my network to force specific DNS to all clients in LAN, even if the clients try to use other DNS like 1.1.1.1.

For cases like ddns-updater or for certificate resolvers via dns challenge, I have exception in the rule for that system.

**Comment by guiweber** [comment]
Yes, I would also have assumed that too. But some functionality is clearly linked to the system's DNS configuration.

What I can tell you is that if I stop DDNS-updater, set the TrueNas DNS in Network -> Global Configuration -> Nameservers, and then restart DDNS-updater, I see the following happen:

Nameservers set to 1.1.1.1:
- DDNS-Updater quickly reaches "Running" state
- In the DDNS-Updater UI, all my domains show as "Up to date"

Nameservers set to 127.0.0.1:
- DDNS-Updater gets stuck in "deploying" state
- In the DDNS-Updater UI, the domain without a dnsmasq rule show as "Up to date" while those with a dnsmasq rule show as "Failure"

Nameservers set to its own LAN IP address:
- DDNS-Updater gets stuck in "deploying" state
- In the DDNS-Updater UI, all domains show as "unset"

Setting a specific `Public IP DNS Providers` doesn't change the results (though I only tested Cloudflare, and "All providers")

**Comment by stavros-k** [comment]
DDNS-Updater will not pass healthcheck if a domain is not "up to date" (this is how healthcheck works for ddns-updater).

In the 3rd scenario, I assume the nameserver is the one provided by your DHCP (and not the truenas IP).
Does this scenario had the dnsmasq rule or not?

**Comment by guiweber** [comment]
My server is on a static IP so no DHCP. The third scenario is the Trunas System's IP address on the LAN.
I point the namserver to the TrueNas system's own address (and 127.0.0.1) since I'm running Pi-Hole on it.
In scenario 2 and 3, with Pi-Hole as the DNS, the dnsmask rules are applied.

**Comment by stavros-k** [comment]
I can now see the whole picture.

So it works when changing the nameservers on TrueNAS to a public one, because the dnsmasq rule cannot be applied anymore. (I usually do those rules on my router/firewall, so noone can escape those).

And yea I can see how `--dns` would work in this case. 
But I'm not sure I want to promote this kind of usage. TrueNAS should never point to itself for DNS.
This creates a chicken and egg scenario, where when the docker tries to spin up pihole but wants DNS to fetch the image, but for DNS to work pihole must be up.

**Comment by guiweber** [comment]
I've been running my instance with the name server configured to 127.0.0.1 for several weeks now and haven't encountered any issues, except for DDNS-updater. It's actually blazing fast :)

But maybe adding the option to add "docker launch parameters" in the app config panel would give some flexibility without encouraging this use case specifically?

In my case, the main router is on a 1G section of the network, while the TrueNas server is on a 10G section of the network. So I need to keep the DNS rules applied to prevent NAT loopback from the router to avoid the bottleneck. Sure, I could run Pi-Hole on another device, but it seems a bit unnecessary since it otherwise works very well running on the TrueNas system.

**Comment by stavros-k** [comment]
> I've been running my instance with the name server configured to 127.0.0.1 for several weeks now and haven't encountered any issues, except for DDNS-updater. It's actually blazing fast :)

The issues will be encountered during updates/upgrades or container restarts where docker tries to resolve dns, but pihole container is not running, and it cannot start pihole without resolving dns. I've wasted a ton of time troubleshooting such issues already.

> But maybe adding the option to add "docker launch parameters" in the app config panel would give some flexibility without encouraging this use case specifically?

Apps are using docker compose, so you cannot have a field for flags, as they don't work for compose. 

> In my case, the main router is on a 1G section of the network, while the TrueNas server is on a 10G section of the network. So I need to keep the DNS rules applied to prevent NAT loopback from the router to avoid the bottleneck. Sure, I could run Pi-Hole on another device, but it seems a bit unnecessary since it otherwise works very well running on the TrueNas system.

I don't see how having the dns rules on truenas vs on the router would affect throughput. 
Clients will only ask the router/fw for an IP afterwards they communicate directly with the given IP.

> IMO its far better to do the rules on the router/fw. As you can also force devices that try to override network settings.
> Tho this won't work for encrypted dns queries. But that's another story.

--- 

For this use case the nameservers field is not going to be exposed. If there is another use case, I'm open to re-visit.

Note that using truenas' self as dns server is not supported and it was actually a bug fixed here.
https://github.com/truenas/middleware/pull/15257
