### ISSUE TITLE
Nextcloud 1.5.6: Can't load site, `NS_ERROR_CORRUPTED_CONTENT`

### ISSUE THREAD

**Issue by 43615** [truenas/apps#1208]
After the update to app version 1.5.6, requests for the homepage fail. I've tried both the external subdomain (via cloudflared) and the local address (:9001).
Firefox shows status 302 and error `NS_ERROR_CORRUPTED_CONTENT`. All incoming requests are correctly logged by the `nginx` and `nextcloud` containers, without any error messages. There are also no obvious errors on startup of those containers.

**Comment by stavros-k** [comment]
Not sure exactly what the issue is without having a full picture of how it is configured and your network.
But if nextcloud does not even log any errors, I'm not sure what I can do here.

**Comment by 43615** [comment]
Poked around a bit, the "External Port" option seems to have fixed it:
![image](https://github.com/user-attachments/assets/83e012ae-1de4-4833-a428-bf68b1bc7b73)
Some setup details: The instance is reachable by a public subdomain, which is managed as a Cloudflare tunnel (`cloudflared` reverse proxy redirecting to `https://hostname:9001`). The "Host" option at the top is set to just the domain, without a port number.
