### ISSUE TITLE
Nextcloud: 'Access through untrusted domain' when accessing over https on a private network

### ISSUE THREAD

**Issue by xixenon** [truenas/apps#1211]
Hello, 

On TrueNAS 24.10.1, after installing a new instance of Nextcloud, I get this error when trying to access it over my local network:

![image](https://github.com/user-attachments/assets/58656710-d230-4c77-9950-f6184238500b)

Despite having the IP and port under trusted domains in `config.php` (192.168.1.124:9001), I still get this error. 
In my experience this issue only occurs when using a SSL certificate. I can access the login screen as expected when using no certificate. As much as I value security, even being on the local network using unencrypted HTTP is a non-solution to me. 

Other users are also having this issue as shown in this post in the TrueNAS forums:
https://forums.truenas.com/t/nextcloud-untrusted-domain/28168

**Comment by xixenon** [comment]
Thanks to da2el in the TrueNAS forums for finding a solution to this. 

https://forums.truenas.com/t/nextcloud-untrusted-domain/28168/8

I am new to writing issues, so I'll leave this issue open for review in case it's noteworthy, I apologize if this is not standard etiquette.

**Comment by stavros-k** [comment]
Not sure exactly what the issue was without having a full picture of how it is setup and how your network is.
Nextcloud is quite complex to setup and its very dependent on the environment used.

Glad you got it working!

Thanks
