### ISSUE TITLE
Feature request - Favorize / heart shared photos

### ISSUE THREAD

**Issue by jockefardig** [truenas/apps#1213]
Hi! Love this software!

I notice that my wifes photos, which I choose to show in timeline, doesn't have the option to favorize / the heart isn't there. It would be great if I could heart her photos and vice versa. Maybe the feature could be toggled on the same way as "show in timeline". "Show partners liked/favorized photos". And if I like a photo that is from her library, that could be saved on my account but she can opt to show/hide my likes...

**Comment by stavros-k** [comment]
I'm not sure what this feature request is for.
It seem you are using one of the many photos app in the catalog or via custom solution.
You should ask that project to add that feature.
