### ISSUE TITLE
wordpress permission problem when using host path

### ISSUE THREAD

**Issue by kakachen001** [truenas/apps#1216]
wordpress is asking for UID 999 but UID 999 is bring used by netdata on my system. any ways to change the uid for mariadb?

UID:
999
GID:
999
Username:
mariadb
Groupname:
mariadb
Description:
MariaDB runs as non-root user.

**Comment by stavros-k** [comment]
Not without building custom container/app stack
https://github.com/MariaDB/mariadb-docker/blob/a6b360fc45b1a8fcd63b87ab69d4ce43566a7c06/main-ubi/Dockerfile#L4
