### ISSUE TITLE
qbittorrent memory issue

### ISSUE THREAD

**Issue by dflesch28** [truenas/apps#1217]
TrueNas Scale 24.10
qbittorrent Truenas app: App version - 5.0.3, version - 1.1.11

Fresh install of app after upgrading to Truenas Scale 24.10, when downloading in qbittorrent, RAM will steadily climb until it hits memory limit in container. When hitting the limit, app will crash and redeploy. Started first with 4gb memory limit and then increased to 16gb limit with same result.

App crash and redeploy cancels and restarts active torrent downloads. Also, memory leak only increases during an active download and does not seem to happen during upload. Memory used will not reset after a download completes and will only reset with container restart.

Attached screenshot of logs. Memory limit hit at '2024-12-22 14:59:11'

![Qbittorrent_logs](https://github.com/user-attachments/assets/d5f69c3a-d4c4-4109-a3f4-a9fe03d5bade)

Reviewed both Truenas and qbittorrent forums for relative issues but was unable to find anything pertaining to this issue.

**Comment by stavros-k** [comment]
Hello, you should probably report this upstream. There is nothing we can do on our side.
Thanks
