### ISSUE TITLE
Emby app only exposes the HTTP but doesnt expose the HTTPS and theres no way to change it in the config

### ISSUE THREAD

**Issue by robin-nathan** [truenas/apps#1218]
![image](https://github.com/user-attachments/assets/f088e264-75d4-4a85-a7ed-26fd13149a79) During the configuration of the emby app it only allows you to set the port for the HTTP and not the HTTPS even though HTTPS is setup in the emby app

**Comment by fedekrum** [comment]
The same happens with WG Easy if you force https on web connections. I can't access its web UI.

**Comment by stavros-k** [comment]
Both those apps do not have a way to enable/disable https with flags or environment variables (that I know of).

So there is no way to adapt healthcheck when you change to https.
Only thing I can offer is a checkbox that will only adapt the healthcheck for https, you will still need to setup the rest with the app.

**Comment by stavros-k** [comment]
> The same happens with WG Easy if you force https on web connections. I can't access its web UI. SSL Cert is made with letsencypt. It is not an option for me not to force https.

Can you show how you force https? I don't see that option in wg easy webui

**Comment by fedekrum** [comment]
There is no option in wg-easy. It was Firefox an chrome forcing a https connection. I access it through a FQDN from the internet. The option was to disable the forced redirect in Firefox.
