### ISSUE TITLE
Unable to update apps after upgrade to 24.10.1

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/apps#1224]
Me and several other users on the Discord server are experiencing this problem. After upgrading to 24.10.1 the following error pops up when trying to update an app that uses the `iXvolume` storage type:

`File "/mnt/.ix-apps/app_configs/wg-easy/versions/1.1.5/templates/library/base_v2_1_5/validations.py", line 171, in allowed_fs_host_path_or_raise
    raise RenderError(f"Path [{path}] is not allowed to be mounted.")
base_v2_1_5.error.RenderError: Path [/mnt/.ix-apps/app_mounts/wg-easy/config] is not allowed to be mounted.`

- Unset + set pool did not fix it, no permissions have been changed by the user.
- Already installed apps start/stop just fine.
- Apps that have no `iXvolume` storage type update just fine. 
- Installation of new apps using the `iXvolume` storage type gives the same error

Full log included:

[message.txt](https://github.com/user-attachments/files/18229849/message.txt)

**Comment by S1lencio** [comment]
This was apparently fixed with this PR: https://github.com/truenas/apps/pull/1220
But I dont think the apps list in Truenas has updated yet. I still get this error as well.

**Comment by TimvanDijkNL** [comment]
It also happens with custom apps, though... the only thing they all have in common is the `ixVolume` storage
