### ISSUE TITLE
Nextcloud spamming logs with "cURL error 7: Failed to connect"

### ISSUE THREAD

**Issue by strich3** [truenas/apps#1229]
It seems like it wants to connect to something, but I don't know what and why.

Log:
![image](https://github.com/user-attachments/assets/e156494e-3561-410e-bb21-3500b846949a)

**Comment by stavros-k** [comment]
Can you share a bit more details?
What is this IP? Where that port is used on? 
When did that start happening?

**Comment by stavros-k** [comment]
Can you run this on truenas host? Maybe we can see where that port is used.
```sh
docker ps
```

**Comment by stavros-k** [comment]
Try expanding one of the error messages? Maybe there are more details there?

**Comment by stavros-k** [comment]
I'd say check your config.php or other apps installed / configured in the admin panel, see if anything specifies that IP.
Not exactly sure why nextcloud tries to reach this IP tbh.
