### ISSUE TITLE
The Status of Jellyfin stuck at DEPLOYING even if it runs normally

### ISSUE THREAD

**Issue by ramondsq** [truenas/apps#1237]
I have to set Additional Environment Variables for Jellyfin for some reason as shown below. 

![1735226248911](https://github.com/user-attachments/assets/72771976-a4a0-4078-b570-7edead411a71)

But if I do so, the Status of Jellyfin would stuck at **Deploying**, even if it starts normally. Everything else works fine. 

![image](https://github.com/user-attachments/assets/5693bca0-31ad-484f-98a5-4836c9eaad2b)

**Comment by stavros-k** [comment]
Does this help? https://github.com/truenas/apps/issues/807#issuecomment-2457349655

**Comment by ramondsq** [comment]
> Does this help? [#807 (comment)](https://github.com/truenas/apps/issues/807#issuecomment-2457349655)

It helps. Thanks. 

I added env variable `no_proxy` with value `192.168.*.*,*.local,localhost,127.0.0.1`
