### ISSUE TITLE
Community Chart Suggestion: Calibre and Calibre-Web

### ISSUE THREAD

**Issue by tancak** [truenas/apps#158]

**Comment by stavros-k** [comment]
Can anyone clarify if calibre is something different than calibre-server?
When I run calibre I see a UI like this.

![image](https://github.com/user-attachments/assets/68a20489-6d3e-41af-aad5-02fd37df8371)

But **NOT** 
![image](https://github.com/user-attachments/assets/9382905e-3056-46ed-8fb2-20c0846faa3d)

Which is the "correct" one?
The second one feels like a desktop app?!

**Comment by xxyzz** [comment]
calibre is a desktop app, the first pic is the content server enabled from the "Connect/share" button in the second pic.

calibre-web is a web ui for calibre's database file.

**Comment by stavros-k** [comment]
I see, so in my case the one I currently have as Draft only has the calibre content server. 
Which I assume is not the "main" think we want here. I'll switch it up for the "desktop" app + content server.

Meanwhile enjoy the already added calibre-web
