### ISSUE TITLE
Community Chart Suggestion: GitHub Actions Runner Controller

### ISSUE THREAD

**Issue by Simoneu01** [truenas/apps#180]
- https://github.com/actions/actions-runner-controller/tree/master/charts/actions-runner-controller
- https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller

**Comment by stavros-k** [comment]
Given that there is no k8s in 24.10 and later. this is not possible.
Closing

Thanks
