### ISSUE TITLE
Community Chart Suggestion : Steam Headless server

### ISSUE THREAD

**Issue by Maxoobidou** [truenas/apps#211]
Hello there,

Would you consider having the Steam Headless server as an official chart ?

Here is the github: https://github.com/Steam-Headless/docker-steam-headless

Would be greatly appreciated !

**Comment by stavros-k** [comment]
Please follow #251 for updates!
(Closing this one even if its older as the other is already associated with a jira ticket).
But app request is still valid!

Thanks!
