### ISSUE TITLE
24.10 Beta 1: Tailscale Advertise Routes not working

### ISSUE THREAD

**Issue by dukeside** [truenas/apps#315]
Advertise routes feature not working, workaround is to use: Additional Environment Variables. Name: TS_ROUTES Value: Whatever you would normally use.

**Comment by elvisimprsntr** [comment]
I tired the work around suggested by the OP, but I still get the following error via the Admin Console

<img width="481" alt="Screenshot 2024-09-25 at 2 03 30 AM" src="https://github.com/user-attachments/assets/6c86efaf-09c8-4e3f-8a03-6abf5ecbd216">
