### ISSUE TITLE
Community Chart Suggestion: Ollama

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/apps#319]
https://github.com/ollama/ollama

**Comment by stavros-k** [comment]
Does https://github.com/open-webui/open-webui also covers this? (Getting added here https://github.com/truenas/apps/pull/686)
Or it makes sense to also have it as a separate app?

**Comment by InfiniteBed** [comment]
Openwebui is only a frontend application, to my knowledge. It connects to ollama through http.

**Comment by InfiniteBed** [comment]
I was not aware ollama could be bundled-in. Learned something today. Great to see lots of work being made on truenas
