### ISSUE TITLE
24.10 Beta 1: Nginx Proxy Manager stuck on Setting ownership ...

### ISSUE THREAD

**Issue by pierrickrouxel** [truenas/apps#322]
On a fresh install, with default values:
The container starts with this log:

```
2024-08-30 10:41:13.439060+00:00[1;34m❯ [1;36mConfiguring npm user ...[0m
2024-08-30 10:41:14.887873+00:00useradd warning: npm's uid 568 outside of the UID_MIN 1000 and UID_MAX 60000 range.
2024-08-30 10:41:16.571624+00:00[1;34m❯ [1;36mConfiguring npm group ...[0m
2024-08-30 10:41:17.919923+00:00[1;34m❯ [1;36mChecking paths ...[0m
2024-08-30 10:41:18.233081+00:00[1;34m❯ [1;36mSetting ownership ...[0m
```

It stick indefinitely on the last line.

**Comment by stavros-k** [comment]
It is known issue (https://github.com/truenas/charts/issues/1212)
But can you check if, for example, after 30minutes, are the log timestamps the same, or are they shifted in time?

Thanks

**Comment by pierrickrouxel** [comment]
Finally it starts but it took 30mn Oo.
It runs on a Intel(R) Xeon(R) CPU E3-1265L V2 @ 2.50GHz with 16GB of RAM and others containers work normally.

```
...
2024-08-30 10:41:18.233081+00:00[1;34m❯ [1;36mSetting ownership ...[0m
2024-08-30 11:09:15.142989+00:00[1;34m❯ [1;36mDynamic resolvers ...[0m
...
```

**Comment by pierrickrouxel** [comment]
> It is known issue ([truenas/charts#1212](https://github.com/truenas/charts/issues/1212)) But can you check if, for example, after 30minutes, are the log timestamps the same, or are they shifted in time?
> 
> Thanks

In my case it runs in `/mnt/.ix-apps`. If I understand the system correctly, it's in my boot device that is an SSD.

**Comment by stavros-k** [comment]
CPU is not the issue here. Is how the overlay fs works with ZFS and the container doing operations that happen in immutable container layers. and every layer that is touched an new overlayed fs has to be created.

`/mnt/.ix-apps` is in the apps pool you selected. 
Just mounted on a different location

**Comment by pierrickrouxel** [comment]
Ok thank you for the explantions.

Will you integrate the workaround in truenas app?

**Comment by pierrickrouxel** [comment]
Ok thank you for your time!

**Comment by pierrickrouxel** [comment]
@stavros-k 
There is an issue with apps. I can't apply the workarround since environment variables are incorrectly handled in apps.


```
S6_STAGE2_HOOK=sed -i '$d' /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
```

become in logs:

```
/run/s6/basedir/scripts/rc.init: warning: hook sed -i '' /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh exited 1
```

I tried combinations of quote or \ without success. The $d variable is always replaced.

**Comment by stavros-k** [comment]
Escape `$` with another `$`
eg `$$d`

Docker tries to expand variables otherwise

**Comment by pierrickrouxel** [comment]
It's ok! Thank you.
