### ISSUE TITLE
Pi-hole : Unable to make changes to dns settings.

### ISSUE THREAD

**Issue by gammerboy** [truenas/apps#329]
Truenas Scale version: 22.10 Beta 1
Truenas pihole app version: 1.1.2

The interface keeps reverting back to the default options when the save button is clicked. dnsleaktest shows the dns server as ones from cleanbrowsing.org

![image](https://github.com/user-attachments/assets/67b29e29-fa9c-4039-b515-056cac8fbba7)

**Comment by stavros-k** [comment]
Some pihole settings must be managed via env variables.
UI changes will revert back to the default values of what pihole defines.
See here for a list of envs
https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#environment-variables

**Comment by gammerboy** [comment]
Another instance of pihole I had running on a raspberry pi without additional/optional envs used to allow me to make changed to the dns settings on the UI.

**Comment by stavros-k** [comment]
Probably this is the issue you are experiencing:
https://github.com/pi-hole/docker-pi-hole/issues/1623

**Comment by stavros-k** [comment]
Can yoiu also check the logs as well? Maybe save fails due to permissions issues?

**Comment by gammerboy** [comment]
It does seem to be issue with permissions.

![image](https://github.com/user-attachments/assets/b58f1e44-ef1c-4b33-a43f-9269cf9cb666)
