### ISSUE TITLE
Mealie Install issue - EE

### ISSUE THREAD

**Issue by NightShaman** [truenas/apps#380]
When trying to install a fresh instance of Mealie, I get an error that the DB is unhealthy. Almost like the app is not waiting long enough for the db to be created and come up as healthy. I am using Host path for both config and postgres data. 

[EFAULT] Failed 'up' action for 'mealie' app: Network ix-mealie_default Creating Network ix-mealie_default Created Container ix-mealie-permissions-1 Creating Container ix-mealie-permissions-1 Created Container ix-mealie-postgres-1 Creating Container ix-mealie-postgres-1 Created Container ix-mealie-mealie-1 Creating Container ix-mealie-mealie-1 Created Container ix-mealie-permissions-1 Starting Container ix-mealie-permissions-1 Started Container ix-mealie-permissions-1 Waiting Container ix-mealie-permissions-1 Exited Container ix-mealie-postgres-1 Starting Container ix-mealie-postgres-1 Started Container ix-mealie-postgres-1 Waiting Container ix-mealie-permissions-1 Waiting Container ix-mealie-permissions-1 Exited Container ix-mealie-postgres-1 Error dependency failed to start: container ix-mealie-postgres-1 is unhealthy

**Comment by NightShaman** [comment]
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'mealie' app:  Network ix-mealie_default  Creating
 Network ix-mealie_default  Created
 Container ix-mealie-permissions-1  Creating
 Container ix-mealie-permissions-1  Created
 Container ix-mealie-postgres-1  Creating
 Container ix-mealie-postgres-1  Created
 Container ix-mealie-mealie-1  Creating
 Container ix-mealie-mealie-1  Created
 Container ix-mealie-permissions-1  Starting
 Container ix-mealie-permissions-1  Started
 Container ix-mealie-permissions-1  Waiting
 Container ix-mealie-permissions-1  Exited
 Container ix-mealie-postgres-1  Starting
 Container ix-mealie-postgres-1  Started
 Container ix-mealie-postgres-1  Waiting
 Container ix-mealie-permissions-1  Waiting
 Container ix-mealie-permissions-1  Exited
 Container ix-mealie-postgres-1  Error
dependency failed to start: container ix-mealie-postgres-1 is unhealthy

**Comment by stavros-k** [comment]
If it installs without issues when using ix-volumes it's most likely permissions issue.
Postgres requires 999:999 for their data directory.

You can also check logs by having a shell window open while installing, and run `docker logs ix-mealie-postgres-1 -f`

**Comment by stavros-k** [comment]
See also https://github.com/truenas/apps/issues/366#issuecomment-2343271394

**Comment by NightShaman** [comment]
Yuh, that was it, I set to 999 and all was right in the world. TY Sir.
