### ISSUE TITLE
immich, why 5 different storage path?

### ISSUE THREAD

**Issue by Simoneu01** [truenas/apps#411]
Why do we have 5 different storage paths for immich?

I see that on the official docs and in the official repo they are just using one path:

https://github.com/immich-app/immich/blob/15f9ff1fcb4819ce7d14d0ea068130b119ae3025/docker/docker-compose.prod.yml#L14

https://github.com/immich-app/immich-charts/blob/31a0787e809e2cc33888a7518a234724ca896317/charts/immich/templates/server.yaml#L82

why are we forced to have 5 for immich? This is over complicating everything for the end user. 

Is someone wants really to have 5 different path can use the "additional paths" instead of being forced to create 5 dataset

**Comment by InfiniteBed** [comment]
The reason for this is, those five datasets are under one central dataset, which is the upload folder that you see in the official compose. Absolutely agree, it should only be 1 dataset.

**Comment by stavros-k** [comment]
Different paths for different purposes.

That way you can have either everything under 1 place (defining the same base dataset with different subdirs) OR have each thing on a different place

eg
cache on fast nvmes (maybe even throwaway nvmes)
thumbs on ssds (maybe even throwaway ssds)
media on hdds with all the data protections etc.

How would you do that with a single path?

That being said, there isn't something that can change at this point, without breaking existing installations.
And if it was changed, I'm sure people would come asking to re-add this (as it was done for nextcloud)

**Comment by NicholasFlamy** [comment]
https://immich.app/docs/guides/custom-locations/
![Screenshot 2024-11-11 173501](https://github.com/user-attachments/assets/6007a9e0-af8e-4e9c-a677-b1362be3009c)
The upload and library mounts should be combined to prevent excessive wear.
