### ISSUE TITLE
Paperless-ngx unable to connect to Redis running on TrueNAS SCALE ElectricEel 24.10 BETA

### ISSUE THREAD

**Issue by Adolar13** [truenas/apps#418]
When installing and starting the paperless-ngx app from within TrueNAS SCALE ElectricEel 24.10 BETA, the main container fails to connect to the redis container. Here is the log:

2024-09-14 10:24:55.780002+00:00Paperless-ngx docker container starting...
2024-09-14 10:24:55.794529+00:00Creating directory scratch directory /tmp/paperless
2024-09-14 10:24:55.796517+00:00Adjusting permissions of paperless files. This may take a while.
2024-09-14 10:24:55.814248+00:00Waiting for PostgreSQL to start...
2024-09-14 10:24:55.865888+00:00Connected to PostgreSQL
2024-09-14 10:24:56.376697+00:00Traceback (most recent call last):
2024-09-14 10:24:56.376770+00:00File "/sbin/wait-for-redis.py", line 24, in <module>
2024-09-14 10:24:56.376821+00:00with Redis.from_url(url=REDIS_URL) as client:
2024-09-14 10:24:56.376721+00:00Waiting for Redis...
2024-09-14 10:24:56.376920+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-14 10:24:56.377052+00:00File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 144, in from_url
2024-09-14 10:24:56.377133+00:00connection_pool = ConnectionPool.from_url(url, **kwargs)
2024-09-14 10:24:56.377151+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-14 10:24:56.377167+00:00File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 959, in from_url
2024-09-14 10:24:56.377359+00:00url_options = parse_url(url)
2024-09-14 10:24:56.377411+00:00^^^^^^^^^^^^^^
2024-09-14 10:24:56.377438+00:00File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 858, in parse_url
2024-09-14 10:24:56.377635+00:00url = urlparse(url)
2024-09-14 10:24:56.377661+00:00^^^^^^^^^^^^^
2024-09-14 10:24:56.377676+00:00File "/usr/local/lib/python3.11/urllib/parse.py", line 395, in urlparse
2024-09-14 10:24:56.377849+00:00splitresult = urlsplit(url, scheme, allow_fragments)
2024-09-14 10:24:56.377898+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-14 10:24:56.377922+00:00File "/usr/local/lib/python3.11/urllib/parse.py", line 497, in urlsplit
2024-09-14 10:24:56.378124+00:00raise ValueError("Invalid IPv6 URL")
2024-09-14 10:24:56.378181+00:00ValueError: Invalid IPv6 URL

Only required fields were set during paperless setup and all default options were used.

**Comment by stavros-k** [comment]
Hello, can you tell me if the redis password contains any special characters? If yes, can you also share those special characters? And if possible the complete password (Assuming is a random generated one).

Thanks

**Comment by stavros-k** [comment]
Okay, so the `)` and `]` are causing the issue in this case (paperless parses the redis connection string as url)
And confuses it with ipv6 for some reason.

The error for postgres, is because you reinstalled the application with the same name using ix-volumes.
Removing the app does not remove the ix-volumes, so a volume left around with the old postgres data (and old postgres password).

Try with a new app name, and don't use special characters on Redis password.
This should work.

**Comment by Adolar13** [comment]
Unfortunately the other error still occurs using a different app name or cleaning ix-volumes from shell manually. :(

**Comment by stavros-k** [comment]
Can I have the output of this?
```sh
midclt call app.config paperless-ngx123 | jq
```

NOTE: this will contain the passwords you entered in the UI for this app.
Feel free to redact them, but ideally I would like with the original values, but only leave them if they are random generated. 

Thanks!

**Comment by Adolar13** [comment]
{
  "TZ": "Europe/Berlin",
  "ix_certificate_authorities": {},
  "ix_certificates": {},
  "ix_context": {
    "app_metadata": {
      "app_version": "2.12.0",
      "capabilities": [
        {
          "description": "Paperless-ngx is able to chown files.",
          "name": "CHOWN"
        },
        {
          "description": "Paperless-ngx is able to bypass permission checks.",
          "name": "DAC_OVERRIDE"
        },
        {
          "description": "Paperless-ngx is able bypass permission checks for it's sub-processes.",
          "name": "FOWNER"
        },
        {
          "description": "Paperless-ngx is able to set group ID for it's sub-processes.",
          "name": "SETGID"
        },
        {
          "description": "Paperless-ngx is able to set user ID for it's sub-processes.",
          "name": "SETUID"
        }
      ],
      "categories": [
        "productivity"
      ],
      "description": "Paperless-ngx is a document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.",
      "home": "https://docs.paperless-ngx.com",
      "host_mounts": [],
      "icon": "https://media.sys.truenas.net/apps/paperless-ngx/icons/icon.svg",
      "keywords": [
        "document",
        "management"
      ],
      "last_update": "2024-09-14 07:20:13",
      "lib_version": "1.0.2",
      "lib_version_hash": "4d8ed8593eb4333a91c4e64cfb5fd4fc790c30a512581315c34bc9aca08f44ff",
      "maintainers": [
        {
          "email": "dev@ixsystems.com",
          "name": "truenas",
          "url": "https://www.truenas.com/"
        }
      ],
      "name": "paperless-ngx",
      "run_as_context": [
        {
          "description": "Paperless-ngx runs as root user.",
          "gid": 0,
          "group_name": "root",
          "uid": 0,
          "user_name": "root"
        },
        {
          "description": "Postgres runs as non-root user.",
          "gid": 999,
          "group_name": "postgres",
          "uid": 999,
          "user_name": "postgres"
        },
        {
          "description": "Redis runs as a non-root user and root group.",
          "gid": 1001,
          "group_name": "root",
          "uid": 0,
          "user_name": "redis"
        }
      ],
      "screenshots": [
        "https://media.sys.truenas.net/apps/n8n/screenshots/screenshot1.png",
        "https://media.sys.truenas.net/apps/n8n/screenshots/screenshot2.png",
        "https://media.sys.truenas.net/apps/n8n/screenshots/screenshot3.png",
        "https://media.sys.truenas.net/apps/n8n/screenshots/screenshot4.png"
      ],
      "sources": [
        "https://hub.docker.com/r/paperlessngx/paperless-ngx",
        "https://github.com/paperless-ngx/paperless-ngx"
      ],
      "title": "Paperless-ngx",
      "train": "community",
      "version": "1.0.3"
    },
    "app_name": "paperless",
    "is_install": true,
    "is_rollback": false,
    "is_update": false,
    "is_upgrade": false,
    "operation": "INSTALL",
    "upgrade_metadata": {}
  },
  "ix_volumes": {
    "consume": "/mnt/.ix-apps/app_mounts/paperless/consume",
    "data": "/mnt/.ix-apps/app_mounts/paperless/data",
    "media": "/mnt/.ix-apps/app_mounts/paperless/media",
    "postgres_data": "/mnt/.ix-apps/app_mounts/paperless/postgres_data",
    "trash": "/mnt/.ix-apps/app_mounts/paperless/trash"
  },
  "network": {
    "web_port": 30070
  },
  "paperless": {
    "additional_envs": [],
    "admin_mail": [redacted],
    "admin_password": "!^uZA4d*Y?N:n(f>",
    "admin_user": "pw",
    "db_password": "EC2$fC:M+31V7cv",
    "enable_trash": true,
    "redis_password": "wvg5fbabQ3tq",
    "secret_key": "==:#g%]A<4j??e6"
  },
  "release_name": "paperless",
  "resources": {
    "limits": {
      "cpus": 2,
      "memory": 4096
    }
  },
  "run_as": {
    "group": 568,
    "user": 568
  },
  "storage": {
    "additional_storage": [],
    "consume": {
      "ix_volume_config": {
        "acl_enable": false,
        "dataset_name": "consume"
      },
      "type": "ix_volume"
    },
    "data": {
      "ix_volume_config": {
        "acl_enable": false,
        "dataset_name": "data"
      },
      "type": "ix_volume"
    },
    "media": {
      "ix_volume_config": {
        "acl_enable": false,
        "dataset_name": "media"
      },
      "type": "ix_volume"
    },
    "postgres_data": {
      "ix_volume_config": {
        "acl_enable": false,
        "dataset_name": "postgres_data"
      },
      "type": "ix_volume"
    },
    "trash": {
      "ix_volume_config": {
        "acl_enable": false,
        "dataset_name": "trash"
      },
      "type": "ix_volume"
    }
  }
}

**Comment by stavros-k** [comment]
Thanks. Found the issue. 
I had to escape `$` in dependencies env as well, as docker tries to expand it as a variable.

(Redis still is an issue that is specific to how paperless parses the URL)

As a workaround for now, omit `$` from the password, or wait for the next version.
Thanks

**Comment by Adolar13** [comment]
Thanks a lot!
