### ISSUE TITLE
Migration of Frigate failed

### ISSUE THREAD

**Issue by chepa92** [truenas/apps#429]
```
[{"name": "frigate", "error": "Failed to create app: [EINVAL] values.frigate.mount_usb_bus: Field was not expected\n", "successfully_migrated": false}]
```

I had coral USB configured, how I can workaround it?

**Comment by stavros-k** [comment]
Hello, once the linked PR is merged.
Wait ~15min. Refresh your catalog and run

```
midclt call -job k8s_to_docker.migrate apps-pool
```

(Replace `apps-pool` with your pool name)

**Comment by chepa92** [comment]
[{"name": "frigate", "error": "Failed to create app: [EFAULT] Failed to render compose templates: base_v1_0_2.utils.TemplateException: Expected [ix_volumes] to be set for [ix_volume] type\n", "successfully_migrated": false}]

Didn't helped :)

**Comment by stavros-k** [comment]
> [{"name": "frigate", "error": "Failed to create app: [EFAULT] Failed to render compose templates: base_v1_0_2.utils.TemplateException: Expected [ix_volumes] to be set for [ix_volume] type\n", "successfully_migrated": false}]
> 
> Didn't helped :)

Investigating it as we speak
(Also reported here https://ixsystems.atlassian.net/browse/NAS-131252)
Different error this time. Will let you know soon!

**Comment by stavros-k** [comment]
> [{"name": "frigate", "error": "Failed to create app: [EFAULT] Failed to render compose templates: base_v1_0_2.utils.TemplateException: Expected [ix_volumes] to be set for [ix_volume] type\n", "successfully_migrated": false}]
> 
> Didn't helped :)

https://github.com/truenas/apps/pull/442
