### ISSUE TITLE
Storj app not installing successfully in 24.10

### ISSUE THREAD

**Issue by orrinwitt** [truenas/apps#452]
Not sure if I'm doing something wrong, but I just tried to get the Storj node app installed on two separate truenas machines running Electric Eel 24.10 BETA 1, and both of them hung at 60% for a long time, then failed to deploy. Am I the only one? It's entirely possible I'm missing something, but I followed [the guide on from Truenas](https://www.truenas.com/docs/scale/24.04/scaletutorials/apps/communityapps/addstorjnode/) (updated as recently as 8/15/2024). Even though it was technically written for the old kubernetes app, all the steps sure looked the same.

I can provide more info on the error if needed.

**Comment by stavros-k** [comment]
Hello,
What was the text of the step at 60%?

**Comment by orrinwitt** [comment]
"App installation in progress, pulling images."

![image](https://github.com/user-attachments/assets/5584f331-f485-4995-b10b-a7a9c43d7cd7)

If I look at the event history in truenas, and click on the failed app.create task, the error it shows is:

[EFAULT] Failed 'up' action for 'storj' app: Timed out waiting for response

**Comment by stavros-k** [comment]
I see, I'll try to find a way to work around that, docker does not "complete" the command until all the containers are running.
And in this case the container that generates the identity takes a VERY long time, which times out on middleware side.
Thanks for the info!

**Comment by stavros-k** [comment]
For the time being you could generate the identity on another system and pass it in. So it will skip generation

**Comment by orrinwitt** [comment]
Thank you, @stavros-k ! 
Is that as simple as just downloading the identity binary and moving it to the "identity" dataset?

**Comment by stavros-k** [comment]
> Thank you, @stavros-k ! Is that as simple as just downloading the identity binary and moving it to the "identity" dataset?

Its not a binary, its some certificates. Give me some time, I'll try to fix it soonish!

**Comment by orrinwitt** [comment]
@stavros-k You're amazing! Thank you so much for getting that fixed. And also thanks for your work on RustDesk. I hadn't opened an issue for that, but that didn't work before either, and now it does!
