### ISSUE TITLE
Community Chart Suggestion: zigbee2mqtt

### ISSUE THREAD

**Issue by Michael-droid77** [truenas/apps#532]
https://github.com/Koenkk/zigbee2mqtt

This software is essential to home-assistant in combination to mosquitto.

**Comment by Danit2** [comment]
@stavros-k Cool thanks for the app.

Can you tell me how to find the `serial/by-id` in Truenas Scale? 
`'/dev/serial': No such file or directory`

Thanks

**Comment by Michael-droid77** [comment]
/dev/ttyUSB0

**Comment by stavros-k** [comment]
> @stavros-k Cool thanks for the app.
> 
> Can you tell me how to find the `serial/by-id` in Truenas Scale? `'/dev/serial': No such file or directory`
> 
> Thanks

What kind of device is it?
If its not under `/dev/serial/by-id/` its most likely not detected by the system? (Assuming its a serial device)

**Comment by Danit2** [comment]
> > @stavros-k Cool thanks for the app.
> > Can you tell me how to find the `serial/by-id` in Truenas Scale? `'/dev/serial': No such file or directory`
> > Thanks
> 
> What kind of device is it? If its not under `/dev/serial/by-id/` its most likely not detected by the system? (Assuming its a serial device)

Sorry my fault. 
I have pass the USB to the VM so it was not visible.

Now its working. 
Thanks für app.
