### ISSUE TITLE
Rust desk not working unless "Host network" box is checked.

### ISSUE THREAD

**Issue by orrinwitt** [truenas/apps#533]
Title says it all. Server is up and running, and set up correctly in both clients. All necessary ports are forwarded in router. Without "Host network" box checked, it will not work. Once I checked it, all of a sudden it works.

My suggestion is to either change the default to have this box checked, or to include whatever else would need fixed or configured to make it work otherwise.

Am I missing something obvious? Do I need to be running something additional (like Nginx or Traefik) that manages these ports to allow traffic to the docker containers?

**Comment by stavros-k** [comment]
Hello, mine works (shows ready) without the need of host network.

Of course here I used local network only. but host network does not make a difference as long as the port forward is done correctly.

See here https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/install/
what ports needs to be opened (note that a few are both tcp and udp)

Below are screens from my laptop and the `10.20.30.6` is my server running rust-desk.

<img width="800" alt="image" src="https://github.com/user-attachments/assets/bca8ae50-91ee-433f-8b24-244a7b3ba58f">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/24576359-a529-4e12-b3d5-ac0feea60889">
<img width="482" alt="image" src="https://github.com/user-attachments/assets/ebcd456e-527f-4e98-a6e2-94094eb692f1">


Please share logs and screenshots if you still having issues.

**Comment by orrinwitt** [comment]
So, is it better to use the local ip of the server for the local workstation, and the server.example.com domain name for the remote workstation? I think that may be part of my problem, as i do get the "ready" with the green light on both machines, but the connection was failing.

**Comment by stavros-k** [comment]
It shouldn't matter, as long as the `server.example.com` resolves to the local IP when the machine is inside your network.

If a local workstation resolves `server.example.com` to your public IP, it makes a weird scenario where your traffic goes out your WAN and back to your LAN (kinda, depends on the router and the Hairpin support etc, but still not ideal).

When it fails does it give an error message?
Do you see any logs on the rust-desk container while you are trying to connect?

**Comment by tramix32** [comment]
For me it only works with host network. Yes it works without host_network checked but then I can only connect from the local network. WAN connections are kinda dropped without host network.
