### ISSUE TITLE
Failed to start docker for Applications: Docker service could not be started- RC1

### ISSUE THREAD

**Issue by Professorvennie** [truenas/apps#590]
[debug-truenas-20241002174538.zip](https://github.com/user-attachments/files/17236311/debug-truenas-20241002174538.zip)

I updated to RC1 and can not get docker to work.  I was running the Beta with no issues.  I tried reveriting back to the beta and docker still wont work.  I see on the form that several other people are having this issues as well.  Let me know if you need anything else from me.

**Comment by Redbearded-sudo** [comment]
Sounds like the same problem I'm having but rolling back to Beta boot environment got mine working again.

**Comment by stavros-k** [comment]
Please open issues for system issues at https://ixsystems.atlassian.net/
Here is only for app specific issues.
Thanks
