### ISSUE TITLE
Apps fail to start after migration - "MariaDB is unhealthy"

### ISSUE THREAD

**Issue by Casuallynoted** [truenas/apps#592]
Some apps, such as Castopod and Wordpress, fail to properly start after migration. The error in the app_lifecycle.log is:

container ix-castopod-mariadb-1 is unhealthy
container ix-wordpress-mariadb-1 is unhealthy

but there's not much more information than that. Is it doing proper health checking on these containers?

**Comment by stavros-k** [comment]
Can you please trigger the migration.
And on another tab / shell try running `sudo docker logs ix-castopod-mariadb-1 -f` (it might need to re-run it a few times until the container is started)

So we can capture some logs and see what's wrong there.

Thanks

**Comment by Casuallynoted** [comment]
![image](https://github.com/user-attachments/assets/1c364031-089e-4bbb-8cc0-6ddc0a22077d)
Getting a lot of this over and over

> Can you please trigger the migration. And on another tab / shell try running `sudo docker logs ix-castopod-mariadb-1 -f` (it might need to re-run it a few times until the container is started)
> 
> So we can capture some logs and see what's wrong there.
> 
> Thanks

**Comment by Casuallynoted** [comment]
> Hello, so please stop both apps.
> 
> We will launch a temp container so mariadb can start and shutdown gracefully. Then you will start each app again to upgrade normally.
> 
> If you are using ix-volumes let me know, I can guide you to get the $host_path.
> 
> Fill in the 4 values below an paste it into truenas shell. Once the logs show that it is "started", Press `Ctrl + C` once and wait for it to finish.
> 
> Then start the app.
> 
> ```shell
> app_name="" # eg: castopod
> root_pass="" # See in the webui for root db pass
> db_pass="" # see in the webui for db pass
> host_path="" # see in the webui for hostpath for the mariadb storage. 
> 
> function run() {
>   [ -z "$app_name" ] && echo "app_name is empty" && exit 1
>   [ -z "$root_pass" ] && echo "root_pass is empty" && exit 1
>   [ -z "$db_pass" ] && echo "db_pass is empty" && exit 1
>   [ -z "$host_path" ] && echo "host_path is empty" && exit 1
> 
>   docker run --rm --name $app_name-tempdb \
>     --user 999:999 \
>     -e MARIADB_DATABASE="$app_name" \
>     -e MARIADB_PASSWORD="$db_pass" \
>     -e MARIADB_ROOT_PASSWORD="$root_pass" \
>     -e MARIADB_USER="$app_name" \
>     -e MARIADB_AUTO_UPGRADE="true" \
>     -v "$host_path":/var/lib/mysql \
>     mariadb:10.6.14
> }
> 
> run
> ```

That did it! Both apps are now running!

**Comment by Retterschen** [comment]
i have the same problem with passbolt app after TrueNas Update. Can someone assit in host-path as i am using the ix-volumes and not sure what to add in $host_path?
