### ISSUE TITLE
Ddns-updater stuck on "Deploying" due to "permissions" container

### ISSUE THREAD

**Issue by Casuallynoted** [truenas/apps#604]
At the moment, after a migration, DDNS-Updater will show in the UI as deploying. This seems to be in spite of it running correctly, and is likely due to the exited container named "Permissions", which has run successfully and closed but is possibly causing the health check to fail.

**Comment by stavros-k** [comment]
What is the output of this?

```
docker container inspect ix-ddns-updater-ddns-1 | jq '.[0].State'
```

**Comment by Casuallynoted** [comment]
> docker container inspect ix-ddns-updater-ddns-1 | jq '.[0].State'

Oh shoot, you know what! One of the settings seems to have changed slightly from when I first set up the app. That command gave me an error that pointed me toward that issue, now that it's resolved the app shows as running. Thank you!
