### ISSUE TITLE
24.10 RC2: Error while installing immich

### ISSUE THREAD

**Issue by alexrtp** [truenas/apps#636]
Encountering error while installing immich. All options are kept at default.

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1363, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1360, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 203, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 252, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 240, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 57, in compose_action
    raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'immich' app, please check /var/log/app_lifecycle.log for more details

I found this closed Issue #316 with a similar message. 
Is this a new Issue or is it fixed for the next release?

**Comment by alexrtp** [comment]
it is the first installation of immich on this system.
I tried the installation with "immich-2", but with the same problem

**Comment by stavros-k** [comment]
While the app is installing, have a second tab open in the System > Shell

You can then observer what is failing to start with

```
sudo docker ps
```

Once you see which container fails 

Then run

```
sudo docker logs <container-name> -f
# eg sudo docker logs ix-immich-server-1 -f
```

**Comment by stavros-k** [comment]
You need to re-run the docker ps command a few times until it appears. As it wont show up until it images are pulled and containers are created.

This should help narrow it down
```
docker ps | grep ix-immich
```

**Comment by alexrtp** [comment]
while the deployment there ara for a short moment 3 containers in the list:
ix-immich-pgvectto-1
ix-immich-machine-learn
ix-immich-redis-1
but they disappear immediatly when the error message appears and the command to show the logs, fails with "No such container"

**Comment by stavros-k** [comment]
Okay lets try one of them 

Right after you hit install, keep running this command. 

```sh
sudo docker logs ix-immich-pgvecto-1 -f
```

**Comment by alexrtp** [comment]
it worked, it looks like there is a problem with the Permissions
but how do i solve this?

`chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.
initdb: error: could not access directory "/var/lib/postgresql/data": Permission denied`

**Comment by stavros-k** [comment]
So your settings are not default I assume?
Because ix-volumes (default) have their permissions fixed automatically.

In case you using host paths you have to manually set the permissions. Specifically for postgres, you want user id `999` and group id `999` to have read/write access.

**Comment by alexrtp** [comment]
Yes i am using host paths. With 24.04. there was no manual setting required.
But i assume that these are the subtle differences.
Thank You for your patient help.

**Comment by stavros-k** [comment]
No problem. did it work now?
