### ISSUE TITLE
Problematic icon for Jellyfin

### ISSUE THREAD

**Issue by p0358** [truenas/apps#643]
There is white text on white background, leading to it being invisible. Then it appears as if the logo was just a small Jellyfin icon shoved into left corner instead.

Jellyfin app icon should instead just be the app's icon in 1:1 proportions, instead of the tiny banner with app name shoved into it, as is the case for most other apps.

![obraz](https://github.com/user-attachments/assets/d7ac69c7-ade3-41b1-80e2-1e1169b9230b)
![obraz](https://github.com/user-attachments/assets/5c5de51f-8420-428f-a21b-9b9190f02e6a)
![obraz](https://github.com/user-attachments/assets/6b982fe1-7fcd-40cd-be1a-2bdea20025cd)

**Comment by stavros-k** [comment]
Fixed! Thanks!
