### ISSUE TITLE
gitea problem after migration

### ISSUE THREAD

**Issue by warcow105** [truenas/apps#659]
I upgraded to 24.10 RC and seem to be having a problem with gitea after migration. The container keeps trying to start without success.

docker logs reports this repeatedly:
`chmod: /tmp/gitea: Operation not permitted`
`/tmp/gitea is not writable`
`docker setup failed`

This is just for cloning my github repos for a local backup, so it is no big deal if I have to wipe it, but it would be great if it didn't come to that.

**Comment by stavros-k** [comment]
Can you please share the logs of the permission container?

**Comment by warcow105** [comment]
2024-10-14 14:50:52.704586+00:00Path [/mnt/postgres/tmp] is a temporary directory, ensuring it is empty...
2024-10-14 14:50:52.705466+00:00Current Ownership and Permissions on [/mnt/postgres/tmp]:
2024-10-14 14:50:52.706328+00:00chown: 0 0
2024-10-14 14:50:52.707219+00:00chmod: 1777
2024-10-14 14:50:52.708118+00:00Ownership is incorrect. Fixing...
2024-10-14 14:50:52.708162+00:00Skipping permissions check, chmod is false
2024-10-14 14:50:52.708178+00:00Changing ownership to 999:999 on: [/mnt/postgres/tmp]
2024-10-14 14:50:52.709162+00:00Finished changing ownership
2024-10-14 14:50:52.709186+00:00Ownership after changes:
2024-10-14 14:50:52.709751+00:00999 999
2024-10-14 14:50:52.711264+00:00Path [/mnt/postgres/data] is not empty, skipping...

**Comment by stavros-k** [comment]
Can I have the contents of this file? (Remember to mask/redact any passwords)

```sh
cat /mnt/.ix-apps/app_configs/gitea/versions/1.0.10/templates/rendered/docker-compose.yaml
```

Thanks!

**Comment by warcow105** [comment]
> Can I have the contents of this file? (Remember to mask/redact any passwords)
> 
> ```shell
> cat /mnt/.ix-apps/app_configs/gitea/versions/1.0.10/templates/rendered/docker-compose.yaml
> ```
> 
> Thanks!

I think I got all the passwords/keys
[comp.txt](https://github.com/user-attachments/files/17367117/comp.txt)

**Comment by stavros-k** [comment]
> 2024-10-14 14:50:52.704586+00:00Path [/mnt/postgres/tmp] is a temporary directory, ensuring it is empty... 2024-10-14 14:50:52.705466+00:00Current Ownership and Permissions on [/mnt/postgres/tmp]: 2024-10-14 14:50:52.706328+00:00chown: 0 0 2024-10-14 14:50:52.707219+00:00chmod: 1777 2024-10-14 14:50:52.708118+00:00Ownership is incorrect. Fixing... 2024-10-14 14:50:52.708162+00:00Skipping permissions check, chmod is false 2024-10-14 14:50:52.708178+00:00Changing ownership to 999:999 on: [/mnt/postgres/tmp] 2024-10-14 14:50:52.709162+00:00Finished changing ownership 2024-10-14 14:50:52.709186+00:00Ownership after changes: 2024-10-14 14:50:52.709751+00:00999 999 2024-10-14 14:50:52.711264+00:00Path [/mnt/postgres/data] is not empty, skipping...

Hmm can you check the logs of permissions container again? There should be more logs

**Comment by warcow105** [comment]
> > 2024-10-14 14:50:52.704586+00:00Path [/mnt/postgres/tmp] is a temporary directory, ensuring it is empty... 2024-10-14 14:50:52.705466+00:00Current Ownership and Permissions on [/mnt/postgres/tmp]: 2024-10-14 14:50:52.706328+00:00chown: 0 0 2024-10-14 14:50:52.707219+00:00chmod: 1777 2024-10-14 14:50:52.708118+00:00Ownership is incorrect. Fixing... 2024-10-14 14:50:52.708162+00:00Skipping permissions check, chmod is false 2024-10-14 14:50:52.708178+00:00Changing ownership to 999:999 on: [/mnt/postgres/tmp] 2024-10-14 14:50:52.709162+00:00Finished changing ownership 2024-10-14 14:50:52.709186+00:00Ownership after changes: 2024-10-14 14:50:52.709751+00:00999 999 2024-10-14 14:50:52.711264+00:00Path [/mnt/postgres/data] is not empty, skipping...
> 
> Hmm can you check the logs of permissions container again? There should be more logs

Just restarted gitea and that is all that is in the permissions container log:
`2024-10-15 15:41:13.322985+00:00Path [/mnt/postgres/tmp] is a temporary directory, ensuring it is empty...`
`2024-10-15 15:41:13.323875+00:00Current Ownership and Permissions on [/mnt/postgres/tmp]:`
`2024-10-15 15:41:13.324767+00:00chown: 0 0`
`2024-10-15 15:41:13.325665+00:00chmod: 1777`
`2024-10-15 15:41:13.326566+00:00Ownership is incorrect. Fixing...`
`2024-10-15 15:41:13.326606+00:00Skipping permissions check, chmod is false`
`2024-10-15 15:41:13.326624+00:00Changing ownership to 999:999 on: [/mnt/postgres/tmp]`
`2024-10-15 15:41:13.327583+00:00Finished changing ownership`
`2024-10-15 15:41:13.327612+00:00Ownership after changes:`
`2024-10-15 15:41:13.328116+00:00999 999`
`2024-10-15 15:41:13.329697+00:00Path [/mnt/postgres/data] is not empty, skipping...`

Michael

**Comment by warcow105** [comment]
I will add that I opened a shell and did a docker ps and the permissions container wasn't listed.  Only the gitea-rootless and gitea-postgres containers were there.  I am very new to docker so that may be normal for all I know.

Michael

**Comment by stavros-k** [comment]
I found the issue. 
Will be fixed once the linked PR is merged.

Thanks
