### ISSUE TITLE
Frigate Allow Coral M2

### ISSUE THREAD

**Issue by jww-cw** [truenas/apps#676]
@stavros-k If possible could we pass though /dev/apex_0 and /dev/bus/usb when the USB option is enabled in the Frigate Community Application. or make and to pass through apex_0?

**Comment by jww-cw** [comment]
could we also add CAP_PERFMON to allow for GPU stats?

**Comment by jww-cw** [comment]
sorry.. maybe bundling a bit into one issue :)  could we also have an option to expose go2rtc which runs on port 1984?

**Comment by stavros-k** [comment]
apex_0 is not a usb right? Does not make sense to bundle it with the usb.
Also what if there are more corals? will there be apex_1?
