### ISSUE TITLE
nexcloud container don't starts

### ISSUE THREAD

**Issue by Juanmallorca1981** [truenas/apps#678]
Hello, I need help to solve a problem in starting the nextcloud container in truenas scale. Some time ago I had the problem of configuring trusted domains and when trying to solve it I found that now the nextcloud container does not start. I put a screenshot of the status and the logs.
thank you so much

![Screenshot_20241019_193340](https://github.com/user-attachments/assets/eebe1d63-9650-40df-af1e-63719ce9e7b7)
![Screenshot_20241019_194234](https://github.com/user-attachments/assets/6df6ac3b-816d-4e69-bd19-ba4e8c4e74d2)

**Comment by stavros-k** [comment]
There seems to be a syntax error on the config.php file in line 38.
Please fix that

**Comment by stavros-k** [comment]
Let me know if there are still issues after that.

Thanks

**Comment by Juanmallorca1981** [comment]
Thanks for the answer, it will be difficult for me to repair the config.php since I do not have access to the container command line and from the teuenas command line I do not know how to access it, I am quite new to truenas, another option I have is to make a backup of the immich container and reinstall truenas to see if hopefully nextcloud works again

**Comment by stavros-k** [comment]
If you used hostpath the config.php is in the place you defined for `html` storage.
if its ix-volume is under `/mnt/.ix-apps/app_mounts/nextcloud/html`

**Comment by Juanmallorca1981** [comment]
Hello, when I tried to solve the problem, I did not use hotspath, I did have access to the nexcloud container shell, I edited the trusted domains, restarted the container and since then I have tried to reinstall the container and it does not start, now I do not have nextcloud installed, would there be any How to be able to delete the volumes and folders that may have been left undeleted to be able to cleanly reinstall the container but in a graphical way?
Thank you,  :)

**Comment by stavros-k** [comment]
You can install using a different name. eg `nextcloud-2`

A UI for managing volumes will probably come later.

**Comment by Juanmallorca1981** [comment]
Good idea, that way different volumes and a different config.php would be created, right? I'll do the test and tell you how it went, thank you very much :)

**Comment by Juanmallorca1981** [comment]
Hello, I already managed to repair nexcloud, in the end what I did was format the pool where nexcloud was located with the rest of the apps that were only immich and reinstall nexcloud, the trusted domains repair message came out again which through the path that you provided me, I have been able to edit the config.php file and everything now works for me, including the mobile phone app
Thank you very much for the help, I have learned a little more about the command line.
Now I just need to learn how to back up the apps and their content in truenas scale
