### ISSUE TITLE
Aguard Home stucks on deploying/starting.

### ISSUE THREAD

**Issue by JMarcosHP** [truenas/apps#707]
On Truenas Scale 24.10 RC2 If you enable https support on Aguard Home and then enable the option "HTTPS Probe" after updating the app, it stucks on Deploying. Then after a couple of minutes the container gets an unhealty state.

Portainer gives more log:
```483B92C7F77F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: ssl_client: SSL_connect wget: error getting response: Connection reset by peer```

**Comment by JMarcosHP** [comment]
It seems that the “Use HTTPS Probe” option breaks something, even after configuring https inside the webui using the network in host mode.

When I configure the same application inside Portainer I don't have this issue and I can enable https without adding extra commands or restart the container.

**Comment by JMarcosHP** [comment]
If you enable https without the option "Use HTTPS Probe" the app works without any issue.

**Comment by stavros-k** [comment]
If you enable the https redirect inside adguard, but NOT check the Use HTTPS probe. Doesn't it go to "unhealthy"?
