### ISSUE TITLE
Gitea installation fails with logs showing dependency postgres "unhealthy"

### ISSUE THREAD

**Issue by zhiyuanzhai** [truenas/apps#711]
Gitea installation now fails with the following error message:
```
[EFAULT] Failed 'up' action for 'gitea' app, please check /var/log/app_lifecycle.log for more details
```
The log file `app_lifecycle.log` shows:
```
 ...
 Container ix-gitea-postgres-1  Waiting
 Container ix-gitea-permissions-1  Exited
 Container ix-gitea-postgres-1  Error
dependency failed to start: container ix-gitea-postgres-1 is unhealthy
```

**Comment by stavros-k** [comment]
If you are using host-paths for postgres data, remember to set the permissions correctly.
postgres data needs `999:999`

**Comment by zhiyuanzhai** [comment]
> If you are using host-paths for postgres data, remember to set the permissions correctly.
> 
> postgres data needs `999:999`
> 
> 

I see. Problem solved by switching to iXVolume for postgre. Thanks!
