### ISSUE TITLE
Immich migrating to ElectricEel-24.10-RC.2 fail. Encrypted dataset and password settings

### ISSUE THREAD

**Issue by Fireflaker** [truenas/apps#712]
Hi,

I have been using Immich in the Apps in version 24.04 and just upgraded to 24.10-RC.2. The reason for the upgrade was ML was not working; GPU could not be attached, and CPU ML returned no people and no context search with errors. All my library directories are encrypted, manually decrypted and I tried manually migrating the app because truenas errored with paths not exist in auto migration when updating. I assumed that was because the dataset was encrypted with passphrase.

I installed the immich app manually and pointed directories to existing unlocked ones. I do not know what to put for the dataset and redis password so I used passphrase for datasets. Unfortunately, I am getting **error: password authentication failed for user "immich"** in immich log and unable to start.

May I ask what should be set for the passphrases for the two new fields(dataset and redis) in the new immich setup when using datasets from the 24.04 old immich?

**Comment by Fireflaker** [comment]
![image](https://github.com/user-attachments/assets/a974e7e3-b703-4ca5-afbf-03e7a55b729c)

In addition, it seems like redis does not like passphrases with spaces as it errors with wrong number of arguments.

And lastly, GPU still cannot be added

**Comment by stavros-k** [comment]
The passwords are not easy to be extracted manually. Migration would have taken care of that if the datasets weren't encrypted.

Now, you have to look into the ix-applications directory, under backups.
Find the last one and de-cipher the kubernetes secrets.

from the top of my head they are double b64 encoded and then gzip encoded

Something like that (replace the `sh.helm.release.v1.homepage.v12` with the correct file name found under the directories mentioned above)

```
echo -n $(cat sh.helm.release.v1.homepage.v12  | grep "^  release:"| cut -f4 -d' ' | base64 -d | base64 -d | gzip -d)
```

**Comment by stavros-k** [comment]
Can you give more information for the GPU issue?

**Comment by Fireflaker** [comment]
There are no words that suffice my thank you @stavros-k. Your few lines of guidance saved me at least a week of headache
Here is a lower entry guide to assist someone having the same issue

To fix migration failure due to encrypted dataset when upgrading immich running on truenas to V24.10
![image](https://github.com/user-attachments/assets/4b927706-d4ec-4ba4-b14f-73cdd672a5e0)
![image](https://github.com/user-attachments/assets/7628d21f-cab8-473a-8898-7ff43920b425)
Lastly, copy the passwords into the respective fields by clicking on edit app settings, save and it came back alive. Note not to include the \n at the end.
