### ISSUE TITLE
Tailscale - Enable "IP Forwarding" on system when deploying as an exit node

### ISSUE THREAD

**Issue by 0xBA5E64** [truenas/apps#738]
Edit: GitHub issues are apparently quite trigger-happy from mobile.

When deploying Tailscale onto a server with the "Exit Node" option ticked, a warning can be seen from the Tailscale web dashboard complaining that the system is not properly set up for IP Forwarding:

![Screenshot_20241030_124328_Firefox](https://github.com/user-attachments/assets/36711a76-83ba-417d-8db6-594b38f2d8b2)

Would it be possible to deploy these changes onto the host system then when the application is installed, despite unfortunately having to reside outside of the confines of the Docker container?

Relevant documentation from above link in screenshot: https://tailscale.com/kb/1019/subnets?tab=linux#enable-ip-forwarding

**Comment by stavros-k** [comment]
No, changes on the host has to be done by you.
Apps can only do actions inside the container.

While there is a way to add sysctl to containers, it only works if the container runs in **non** host-network mode.

**Comment by jankatins** [comment]
Created a PR to point to the right places to change this: https://github.com/truenas/apps/pull/745

**Comment by 0xBA5E64** [comment]
oh crap yeah I just realized you can set sysctl options in the advanced settings, my bad!
Still, I'm sure many others will appreciate the extra heads-up being added yeah
