### ISSUE TITLE
Dockge - Support running as non-root user

### ISSUE THREAD

**Issue by dvcky** [truenas/apps#747]
Hello!

I would like to be able to manage docker services from a non-root user so that the files created from the docker service are in turn also owned by a non-root user. This makes accessing files that are created by the docker services easier to access as that user without changing the file permissions/ownership. Currently, this is not possible through Dockge, as the "User and Group Configuration" section that is available in various other apps (Home Assistant, for example) is not available for it. Would it be possible to add this "User and Group Configuration" section to Dockge?

Thanks!

**Comment by Renari** [comment]
This is something you would need to do within the containers you are launching inside dockage, dockage cannot run without root due to needing access to the docker socket.

**Comment by stavros-k** [comment]
As @Renari said this cannot be done. And even if it could be done (Well it can with some hacking), containers spun up will have their own user/group id context.

Also, in order for user/group configuration to work, the app must support it. Which is why some apps has it and some others don't. Even the ones that do have the option, its different per app.
Some apps run as a whole with the given user, some others run as root but their subprocesses run as the given user.

**Comment by dvcky** [comment]
> This is something you would need to do within the containers you are launching inside dockage, dockage cannot run without root due to needing access to the docker socket.

@Renari This is true, but if the user has access to the docker group then that also works correct? I did forget to ask if this was possible in TrueNAS, my apologies.

> Also, in order for user/group configuration to work, the app must support it. Which is why some apps has it and some others don't. Even the ones that do have the option, its different per app.

@stavros-k I may not have explained my situation properly, I'm sorry if that was the case. An example of what I mean is below:
1. User creates a stack in Dockge called `my_stack` with a volume bind to a relative path `./folder_inside_my_stack`. In the filesystem, a folder is created in the Dockge stacks called `my_stack`, and upon running another is created inside that folder (assuming the folder was not manually created beforehand) called `folder_inside_my_stack` - _both of which are owned by whoever owns the Dockge app._
2. The stack runs, and creates the file `stack_file` in `folder_inside_my_stack`. This file is owned by whoever owns that stack, which can vary depending on the application.

My issue comes with the italicized part - I know it is not possible for the created stacks to inherit the user that Dockge is run by, I simply want the files created by Dockge that aren't created by each of the stacks to be owned by a non-root user. Maybe that is what you are saying and I am misunderstanding it, but I thought I would clarify if that wasn't the case.

**Comment by stavros-k** [comment]
I believe what you want is this?
https://github.com/louislam/dockge/pull/83

**Comment by dvcky** [comment]
That's exactly what I want! Apologies again, I didn't realize this was a Dockge issue and not a TrueNAS issue. Thanks for the help!
