### ISSUE TITLE
ClamAV connection cannot be established

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/apps#749]
Since migrating to Electric Eel, the connection with ClamAV no longer works.

By default, the Nextcloud should reach the Clamd via IP and port, but unfortunately this no longer works.

**Comment by stavros-k** [comment]
You can try to enter nextcloud container and see if you can nc/curl/wget clamav.
But the nextcloud logs suggest a bad parsing on the response?

**Comment by stavros-k** [comment]
> `/bin/sh: 1: nc/curl/wget: not found`

I meant one of the above :D Those are 3 different commands, so each tests different things.

**Comment by stavros-k** [comment]
I found the issue. Will push a fix in a bit
