### ISSUE TITLE
Frigate NVIDIA problem since update to ElectricEel 24.10

### ISSUE THREAD

**Issue by Danit2** [truenas/apps#785]
Since the update, I can no longer start frigate. 
I can no longer add my graphics card. 
Before it worked without any problems. 

I always get the following error: 

```[EFAULT] Failed to render compose templates: base_v1_1_5.utils.TemplateException: Expected [uuid] to be set for GPU inslot [0000:02:00.0] in [nvidia_gpu_selection] ```

What can i do in this case? 

Thanks for help.

**Comment by JamesTaylor92** [comment]
I had a similar issue but was able to resolve it using the details in this ticket:
https://ixsystems.atlassian.net/browse/NAS-132086

**Comment by stavros-k** [comment]
Hello, as @JamesTaylor92 correctly linked, you can follow the steps in this comment
https://ixsystems.atlassian.net/browse/NAS-132086?focusedCommentId=283249

Thanks
