### ISSUE TITLE
Nextcloud app instalation failure when `Nextcloud Postgres Data Storage` is changed to `Host Path`

### ISSUE THREAD

**Issue by vovagorodok** [truenas/apps#790]
Checked `Host Path` as `Apps` and `Generic` Dataset Preset.

Instalation success when  `Nextcloud Postgres Data Storage` is `ixVolume`.

Checked on latest TrueNAS 24.10 and Nextcloud 1.4.2.

Logs:
```
truenas_admin@truenas[~]$ sudo cat /var/log/app_lifecycle.log
[2024/11/03 07:33:03] (ERROR) app_lifecycle.compose_action():56 - Failed 'up' action for 'nextcloud' app:  Network ix-nextcloud_default  Creating
 Network ix-nextcloud_default  Created
 Container ix-nextcloud-permissions-1  Creating
time="2024-11-03T07:32:56-08:00" level=warning msg="config `uid`, `gid` and `mode` are not supported, they will be ignored"
time="2024-11-03T07:32:56-08:00" level=warning msg="config `uid`, `gid` and `mode` are not supported, they will be ignored"
 Container ix-nextcloud-permissions-1  Created
 Container ix-nextcloud-redis-1  Creating
 Container ix-nextcloud-postgres-1  Creating
 Container ix-nextcloud-postgres-1  Created
 Container ix-nextcloud-redis-1  Created
 Container ix-nextcloud-nextcloud-1  Creating
time="2024-11-03T07:32:57-08:00" level=warning msg="config `uid`, `gid` and `mode` are not supported, they will be ignored"
time="2024-11-03T07:32:57-08:00" level=warning msg="config `uid`, `gid` and `mode` are not supported, they will be ignored"
 Container ix-nextcloud-nextcloud-1  Created
 Container ix-nextcloud-permissions-1  Starting
 Container ix-nextcloud-permissions-1  Started
 Container ix-nextcloud-permissions-1  Waiting
 Container ix-nextcloud-permissions-1  Waiting
 Container ix-nextcloud-permissions-1  Exited
 Container ix-nextcloud-postgres-1  Starting
 Container ix-nextcloud-permissions-1  Exited
 Container ix-nextcloud-redis-1  Starting
 Container ix-nextcloud-postgres-1  Started
 Container ix-nextcloud-redis-1  Started
 Container ix-nextcloud-permissions-1  Waiting
 Container ix-nextcloud-postgres-1  Waiting
 Container ix-nextcloud-redis-1  Waiting
 Container ix-nextcloud-permissions-1  Exited
 Container ix-nextcloud-postgres-1  Error
 Container ix-nextcloud-redis-1  Healthy
dependency failed to start: container ix-nextcloud-postgres-1 is unhealthy
```

**Comment by stavros-k** [comment]
If you use hostpath, you have to setup permissions yourself.
In case of postgres its 999:999 ( it should be visible in the run as context card already)

**Comment by Krysztal** [comment]
In my case, access is granted to all users, but installation still failed.

![image](https://github.com/user-attachments/assets/66adc1a1-7580-4fa5-88da-c7c1e3fb5870)

**Comment by stavros-k** [comment]
As I stated above, user 999 and group 999 needs r/w.
user and group here is root.

**Comment by nblky** [comment]
![Uploading Screenshot_20241105_083941_com.microsoft.emmx_edit_305277998240917.jpg…]()

**Comment by nblky** [comment]
> In my case, access is granted to all users, but installation still failed.
> 
> ![image](https://private-user-images.githubusercontent.com/1437474/382739631-0c178caa-d7cf-4481-9dbd-c90aaed702c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Njc0MjAsIm5iZiI6MTczMDc2NzEyMCwicGF0aCI6Ii8xNDM3NDc0LzM4MjczOTYzMS0wYzE3OGNhYS1kN2NmLTQ0ODEtOWRiZC1jOTBhYWVkNzAyYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDAzODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVlZWU2OWIzYjYyYzUwNWRkNjczYWRiOTc5MjJjNTM3ZWZkZmQ5ZDdkNGMxOWJkY2UyM2Q0Zjc3OGU0OGIwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NKRPAc45_sfBpvc2-Mt3wM6UJf_iucpftNrx_fkHwQk)

![Screenshot_20241105_083941_com microsoft emmx_edit_305277998240917](https://github.com/user-attachments/assets/c855c950-e486-4b82-a340-0d02624c38d1)

**Comment by vovagorodok** [comment]
Instalation success only when changed Dataset owner to `netdata (999)`.
It is requirement for `NextCloud postgress database` or `postgress database` or any database?

**Comment by nblky** [comment]
> 仅当将 数据集所有者 更改为 时，安装成功。这是 or 或任何数据库的要求？`netdata (999)``NextCloud postgress database``postgress database`

only pg data

**Comment by vovagorodok** [comment]
Otherwise. If I install another application (not NextCloud) that needs a dataset for postgress database, the owner of that dataset should also be `netdata (999)`?

**Comment by stavros-k** [comment]
postgres in all apps needs a directory with owner user and group to be `999`

**Comment by vovagorodok** [comment]
This is very unclear to new people.
For this moment I see 3 possible solutions:
1. Add additional postgress `Dataset Preset`, which would have the owner as `netdata (999)`
2. Add information about owner requirement for `Nextcloud Postgres Data Storage` during installation process
3. Change Dataset owner automatically like for `Nextcloud AppData Storage (HTML, Custom Themes, Apps, etc.)` and `Nextcloud User Data Storage`, which changes owner to `www-data (33)`

Personally I prefer number 3

**Comment by nblky** [comment]
> > This is very unclear to new people. For this moment I see 3 possible solutions:
> > ```
> > 1. Add additional postgress `Dataset Preset`, which would have the owner as `netdata (999)`
> > 
> > 2. Add information about owner requirement for `Nextcloud Postgres Data Storage` during installation process
> > 
> > 3. Change Dataset owner automatically like for `Nextcloud AppData Storage (HTML, Custom Themes, Apps, etc.)` and `Nextcloud User Data Storage`, which changes owner to `www-data (33)`
> > ```
> 
> There is some generic information in the Run As Context card before and after you install each app. Lists postgres that runs as 999,999
> 
> Automatic permissions is performed **ONLY** on **empty** _ix-volumes_. Which is the only storage we can make sure that does not have custom permissions etc.
> 
> Host paths are managed by the user.

If postgres is used in app,  use host path, The pgData dataset must be owned by the user netdata (UID 999) for postgres to start.

**Comment by nblky** [comment]
> This is very unclear to new people. For this moment I see 3 possible solutions:
> 
> 1. Add additional postgress `Dataset Preset`, which would have the owner as `netdata (999)`
> 2. Add information about owner requirement for `Nextcloud Postgres Data Storage` during installation process
> 3. Change Dataset owner automatically like for `Nextcloud AppData Storage (HTML, Custom Themes, Apps, etc.)` and `Nextcloud User Data Storage`, which changes owner to `www-data (33)`
> 
> Personally I prefer number 3

use host path，Nextcloud AppData Storage and Nextcloud User Data Storage must be owned by the user www-data ，postgres data  must be owned by the user netdata（999:999）

**Comment by vovagorodok** [comment]
Ok, see it:
![image](https://github.com/user-attachments/assets/d035f01c-9716-453a-9bb4-94e1b5d7dff6)
Just `999:999` nothing related to `netdata` name?

**Comment by stavros-k** [comment]
> Ok, see it: ![image](https://private-user-images.githubusercontent.com/8137447/383216542-d035f01c-9716-453a-9bb4-94e1b5d7dff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjMwMjIsIm5iZiI6MTczMDgyMjcyMiwicGF0aCI6Ii84MTM3NDQ3LzM4MzIxNjU0Mi1kMDM1ZjAxYy05NzE2LTQ1M2EtOWJiNC05NGUxYjVkN2RmZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTYwNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxMzIyZTZkMGU3NWI4YWFkMzExZGIxYmQzYTE4OGM2NTNiODRlNWMxYTg1ZDQ1ZTNkYmEyYWIyOWRmNTUyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.evGC5D03rqyg1LGYAcghmVMplCBUZVX6mImCs-mPjx8) Just `999:999` nothing related to `netdata` name?

The user/group name here refers to the user _inside_ the container.
Which is why I always refer to ids and not names.

When there is virtualization/containerization involved, only ids matter. 
Names can be different as long as ids match.

**Comment by nblky** [comment]
> > Ok, see it: ![image](https://private-user-images.githubusercontent.com/8137447/383216542-d035f01c-9716-453a-9bb4-94e1b5d7dff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjMwMjIsIm5iZiI6MTczMDgyMjcyMiwicGF0aCI6Ii84MTM3NDQ3LzM4MzIxNjU0Mi1kMDM1ZjAxYy05NzE2LTQ1M2EtOWJiNC05NGUxYjVkN2RmZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTYwNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxMzIyZTZkMGU3NWI4YWFkMzExZGIxYmQzYTE4OGM2NTNiODRlNWMxYTg1ZDQ1ZTNkYmEyYWIyOWRmNTUyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.evGC5D03rqyg1LGYAcghmVMplCBUZVX6mImCs-mPjx8) Just `999:999` nothing related to `netdata` name?
> 
> The user/group name here refers to the user _inside_ the container. Which is why I always refer to ids and not names.
> 
> When there is virtualization/containerization involved, only ids matter. Names can be different as long as ids match.

![Uploading IMG_20241106_000828.jpg…]()

**Comment by nblky** [comment]
![IMG_20241106_000851](https://github.com/user-attachments/assets/d9560404-1afa-4aa3-aceb-7e56f335ae7e)
![IMG_20241106_000906](https://github.com/user-attachments/assets/96d6153a-7444-42ea-9cb1-584fe09793b8)

**Comment by nblky** [comment]
> > Ok, see it: ![image](https://private-user-images.githubusercontent.com/8137447/383216542-d035f01c-9716-453a-9bb4-94e1b5d7dff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjMwMjIsIm5iZiI6MTczMDgyMjcyMiwicGF0aCI6Ii84MTM3NDQ3LzM4MzIxNjU0Mi1kMDM1ZjAxYy05NzE2LTQ1M2EtOWJiNC05NGUxYjVkN2RmZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTYwNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxMzIyZTZkMGU3NWI4YWFkMzExZGIxYmQzYTE4OGM2NTNiODRlNWMxYTg1ZDQ1ZTNkYmEyYWIyOWRmNTUyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.evGC5D03rqyg1LGYAcghmVMplCBUZVX6mImCs-mPjx8) Just `999:999` nothing related to `netdata` name?
> 
> The user/group name here refers to the user _inside_ the container. Which is why I always refer to ids and not names.
> 
> When there is virtualization/containerization involved, only ids matter. Names can be different as long as ids match.

![Uploading IMG_20241106_000828.jpg…]()

**Comment by vovagorodok** [comment]
One more, that is not clear, `App` or `Generic` or both Dataset Presets can be used for postgress?

**Comment by nblky** [comment]
> One more, that is not clear, `App` or `Generic` or both Dataset Presets can be used for postgress?

![mmexport1730823507010](https://github.com/user-attachments/assets/93d5225f-4c45-4d14-81d5-828d4ce7b4bd)
![mmexport1730823508652](https://github.com/user-attachments/assets/f190f63a-44c4-40ac-9b43-109411d5fa2a)
![mmexport1730823510138](https://github.com/user-attachments/assets/e986b70a-95a5-4f12-96e1-9fe073c26aa9)

**Comment by stavros-k** [comment]
> One more, that is not clear, `App` or `Generic` or both Dataset Presets can be used for postgress?

You need Unix permissions.
Well you can use anything, as long as the following command when run in TrueNAS shell
`ls -la /path/to/postgres/` shows `netdata docker` as owner.

Anything else, will be rejected by postgres. Sadly there is nothing I can do on our side.
Even if postgres CAN write to that location, it will still fail if the owner is not `999:999`.

**Comment by vovagorodok** [comment]
Thanks, now it's clear for me.
I wonder if the experience for newcomers could be improved.
What do You think about adding `Postgres` Dataset Preset that will be `Generic` + `999:999` as owner?

**Comment by stavros-k** [comment]
> Thanks, now it's clear for me. I wonder if the experience for newcomers could be improved. What do You think about adding `Postgres` Dataset Preset that will be `Generic` + `999:999` as owner?

This is not something that can be done on apps side.
You can open a feature request on the forums https://forums.truenas.com/c/features

**Comment by vovagorodok** [comment]
Created: https://forums.truenas.com/t/postgres-dataset-preset/24524
