### ISSUE TITLE
Possibility to disable app limits

### ISSUE THREAD

**Issue by vovagorodok** [truenas/apps#792]
In newer version of apps there no possibility to disable app limits:
![Screenshot from 2024-11-04 10-30-52](https://github.com/user-attachments/assets/474646cf-c702-4bed-8236-77b6727779c4)
Will it be added in the future?

**Comment by stavros-k** [comment]
Hello, even on previous apps there was only on custom app the ability to disable those.
What is the use case that you want to disable those?

You can set your cpu count and memory to the max of what the system has and achieve the same.
But with limits it ensures that a misbehaving app won't starve your system

**Comment by vovagorodok** [comment]
> What is the use case that you want to disable those?

I will use TrueNAS only for one NextCloud app. That's why will be nice to give this app as match resources as it possible?

**Comment by stavros-k** [comment]
You can change the limits to the max of what your system has.

**Comment by vovagorodok** [comment]
I'm wondering about one more case.
What if we change/add RAM or CPU? How app limits will behave in cases when limits are enabled and disabled?
Disabled limits means that them are set to max during app installation (fetched from TrueNAS host system)?

**Comment by stavros-k** [comment]
You can change the values anytime.

**Comment by vovagorodok** [comment]
> You can change the values anytime.

You're right. However, I wonder if the option of setting it to max and not thinking about it in the future wouldn't be better in these cases.

As I correctly understand it will set `resources`  attribute that is optional: https://docs.docker.com/reference/compose-file/deploy/#resources ?

**Comment by stavros-k** [comment]
Yes it sets this attribute.

Unfortunately to change that now, it will require a migration for every app. And I don't think at the moment it will happen as middleware does not have migration support at all (besides the k8s -> docker).

You current options is to manually set it to the desired max value, or use custom app.

**Comment by vovagorodok** [comment]
> Unfortunately to change that now, it will require a migration for every app. And I don't think at the moment it will happen as middleware does not have migration support at all (besides the k8s -> docker).

Sure. Maybe we can consider it on the next release? Should we create somewhere additional issue in order to discuss this case at middleware side?

**Comment by stavros-k** [comment]
Migrations are planned to be added, so there isn't something to discuss there.
But even with support added, this is not a priority, as it will need some time to do the migrations.
And to be honest, I'm not sure that it's worth the time spent.

**Comment by vovagorodok** [comment]
> Migrations are planned to be added, so there isn't something to discuss there.

Just out of curiosity, does this have a dedicated PR or Issue?

> But even with support added, this is not a priority, as it will need some time to do the migrations.

Obviously, there are topics with higher priority, especially after the migration to docker compose

> And to be honest, I'm not sure that it's worth the time spent.

From my PoV it makes sense to allow the user not to limit resources for installed apps. Especially for users who have 1-2 apps

**Comment by vovagorodok** [comment]
@yocalebo why topic was closed without any explanations? There are open ended discussions ongoing
