### ISSUE TITLE
Jellyfin Transcode directory in RAM breaks any trascoding in the app

### ISSUE THREAD

**Issue by hugalafutro** [truenas/apps#818]
updated to EE

1. play file that will direct stream
2. try lowering the bitrate to force transcoding - fatal playback error
3. change Transcode dir to Temporary on Disk in Jellyfin app options
4. Redeploy
5. Everything works including HW transcoding with nvidia card

for reference the path when temporary in ram was:
`/mnt/.ix-apps/docker/volumes/ix-jellyfin_tmp/_data/`
perms were `drwxrwxrwt`

and with temporary on disk it is:
`/mnt/.ix-apps/docker/volumes/ix-jellyfin_config_transcodes/_data`
and perms `drwxr-xr-x`

**Comment by stavros-k** [comment]
Hello, was tmpfs size enough for the transcode?
Can you grab the logs from jellyfin when the error happens?

Thanks

**Comment by hugalafutro** [comment]
I had the logs, but due to who I am as a person I forgot to attach sorry. The tmpfs was set to 500
https://o.o5.ddns.net/yXMc0
https://o.o5.ddns.net/kLVXb

**Comment by stavros-k** [comment]
I dont see anything helpful in the logs,
Can you trying increasing it to lets say 4000.

Also can you shell in the container and navigate to `/config/transcodes` and try to create a file?
eg `touch test.txt`

**Comment by hugalafutro** [comment]
in ram, size 4000
```
I have no name!@truenas:/$ ls -la /config/transcodes/
total 25
drwxr-sr-x 2 root root 40 Nov  5 18:56 .
drwxr-xr-x 9 1000 1000 10 Sep 14 09:24 ..
I have no name!@truenas:/$ touch /config/transcodes/test.txt
touch: cannot touch '/config/transcodes/test.txt': Permission denied
```
