### ISSUE TITLE
expose Privilege mode option in Frigate app to support pcie Coral TPU

### ISSUE THREAD

**Issue by chow11** [truenas/apps#819]
For folks that have turned on developer mode in their Truenas environment and installed the pcie Coral TPU drivers, the Frigate app needs to expose the Security Context Configuration Setting: Privilege checkbox.

Currently this configuration section does not appear in the edit settings page for the app.

**Comment by stavros-k** [comment]
Privileged is usually the last resort to fix permissions issues. I would like to avoid it if possible.
There might be other ways to make it work, but logs are needed. To try to debug. As I dont have the hardware.
