### ISSUE TITLE
Jellyfin: fail to update to 1.1.0

### ISSUE THREAD

**Issue by kabatp** [truenas/apps#829]
TrueNas Scale version 24.10
All apps work OK and I am able to install/rollback/update any of them - The only one with an issue is Jellyfin

I already tried to roll back to 1.0.29 and update from that version but with the same result.

Error message:
`[EFAULT] Failed to render compose templates: Traceback (most recent call last): File "/usr/bin/apps_render_app", line 33, in sys.exit(load_entry_point('apps-validation==0.1', 'console_scripts', 'apps_render_app')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main render_templates_from_path(args.path, args.values) File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path rendered_data = render_templates( ^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates ).render({'ix_lib': template_libs, 'values': test_values}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception() File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "/mnt/.ix-apps/app_configs/jellyfin-new/versions/1.1.0/templates/docker-compose.yaml", line 26, in top-level template code {% do c1.add_storage("/config/transcodes", dict(values.storage.transcodes, **{"tmpfs_config": {"mode": "0777"}})) %} ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/jellyfin-new/versions/1.1.0/templates/library/base_v2_0_11/container.py", line 180, in add_storage self._storage.add(mount_path, config) File "/mnt/.ix-apps/app_configs/jellyfin-new/versions/1.1.0/templates/library/base_v2_0_11/storage.py", line 89, in add volume_mount = VolumeMount(self._render_instance, mount_path, config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/jellyfin-new/versions/1.1.0/templates/library/base_v2_0_11/volume_mount.py", line 73, in __init__ raise RenderError("Expected [volume_config] to be set for [volume] type.") base_v2_0_11.error.RenderError: Expected [volume_config] to be set for [volume] type. `

**Comment by stavros-k** [comment]
Yep, working on it as we speak. 
For now you can change transcode storage to something other than Temporary
Thanks
