### ISSUE TITLE
Question regarding Frigate performance monitoring

### ISSUE THREAD

**Issue by Tenster** [truenas/apps#847]
Hello,

is it possible to add the following capability to frigate to enable monitoring of gpu stats?

 ` cap_add:
      - CAP_PERFMON
`

**Comment by stavros-k** [comment]
Its added recently

https://github.com/truenas/apps/blob/7044e8b1df25bd5e6e9149a6288136ba2d3b4ca0/ix-dev/community/frigate/templates/docker-compose.yaml#L6

Thanks
