### ISSUE TITLE
Readarr onedr0p container no longer maintained

### ISSUE THREAD

**Issue by JimRaynor56** [truenas/apps#860]
The container used for Readarr is no longer maintained.  See: [PR onedr0p/containers#1088](https://github.com/onedr0p/containers/pull/1088)

Possible Alternatives: 
[linuxserver/readarr](https://hub.docker.com/r/linuxserver/readarr)  
[hotio/readarr](https://hub.docker.com/r/hotio/readarr)

I don't know if either would serve as a drop-in replacement.

**Comment by swensorm** [comment]
onedr0p has dropped several containers recently including lidarr and readarr.  I liked the rootless images without s6 et al. but not thrilled about using any when the maintainer will just drop support at will.

Lidarr was switched to an Elfhosted image - very similar in nature to the old.  They have one for Readarr as well:
https://github.com/elfhosted/containers/tree/main/apps/readarr
https://github.com/elfhosted/containers/pkgs/container/readarr-develop

**Comment by stavros-k** [comment]
@swensorm If that's okay, I'll take on readarr this afternoon, while upgrading the image, I'll also upgrade to v2 lib.
