### ISSUE TITLE
Add HTTPS for wg-easy webui

### ISSUE THREAD

**Issue by RickAndTired** [truenas/apps#864]
Feature request:
Add HTTPS for wg-easy webui

**Comment by stavros-k** [comment]
wg-easy does not have built in support for https.
It requires additional/external proxy
https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL

This is not something that will be added on the app itself, as there is already a reverse proxy app you can use (nginx-proxy-manager)
