### ISSUE TITLE
Minio continuous crash and restart

### ISSUE THREAD

**Issue by soubinan** [truenas/apps#865]
Hello,

I just installed the new Truenas version (ElectricEel-24.10.0.2) and tried to add the minio app on it
The installation process goes well until the deployment, where minio ran into an infinite try-crash loop

minio version: 1.1.19

Below the screens of my configs

![image](https://github.com/user-attachments/assets/1cf94f15-8a9c-4086-83bc-883915823166)
Note the behaviour is the same with or without ACLs enabled
![image](https://github.com/user-attachments/assets/06b1e86a-3ef5-4fe8-bc9f-8b08f0798f6a)
![image](https://github.com/user-attachments/assets/d7ace65e-3440-48a1-8fba-f079aa912ede)
![image](https://github.com/user-attachments/assets/296858a5-ec56-444f-9785-cc5b646d105e)

There is no way (afaik) to check the logs since it crash so quickly

**Comment by tieum** [comment]
encountered the same issue, make sure that `/mnt/pool0/S3` is writable by the UID 463 (the one from minio)

```
docker exec ix-minio-minio-1 id
uid=473 gid=473 groups=473
```
