### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by Bl00d-B0b** [truenas/apps#868]
Hello,

A lot of apps, in charts are with pre-defined UTC time zone. and there is no way to change it, even I try to add environment variable TZ, but it's already exist. IS it possible to add time zone setting to each app.

Ed

**Comment by Bl00d-B0b** [comment]
I use those, which do not have Time Zone Settings:
FlareSolverr
Lidarr
Prowlarr
qBittorrent
Radarr
Sonarr
Wordpress

**Comment by stavros-k** [comment]
Are those using the TZ variable? Is there any hints that they do?
I'm just trying to make sure that the options won't be "just there". but are actually useful.
I'd like to avoid issues like "I changed TZ but X feature still use other timezone"

**Comment by Bl00d-B0b** [comment]
when I use Lidarr, Prowlarr, qBittorrent, Radarr, Sonarr from linuxserver docker hub, I can prove, they use it.

**Comment by Bl00d-B0b** [comment]
in wordpress we have two containers. As I can see in wordpress TZ is correct, but in mariadb TZ is missing. I assume it should be same on both.

**Comment by stavros-k** [comment]
For dependency containers, it will be automatically picked up when `v2` lib is used. (its a WIP)
