### ISSUE TITLE
Vaultwarden with SQLite

### ISSUE THREAD

**Issue by MuhKuh7** [truenas/apps#909]
Could you add an option to Vaultwarden to use SQLite instead of PostgreSQL? For only a few users in a low resource environment it would be nice to have the option without the additional PostgreSQL database container overhead.

**Comment by stavros-k** [comment]
Hello, there won't be support for multiple db engines on any application.
Feel free to use one of the custom options (portainer, custom app, etc) to install it with your engine of your liking.

Thanks

**Comment by berlincount** [comment]
I think Vaultwarden should use SQLite by default, and not offer PostgreSQL support at all.
It's complete overkill for most usecases, and makes backups etc so much harder.

see https://github.com/truenas/apps/issues/3166 https://github.com/truenas/apps/issues/1094 etc

As this tends to be a critical application to provide passwords and access to other infrastructure AND is completely self contained with encryption on disk. this would make a lot more sense than the current, unnecessary complex setup.
