### ISSUE TITLE
qbittorrent 1.1.1 can't find downloaded files

### ISSUE THREAD

**Issue by 43615** [truenas/apps#917]
After updating qbittorrent to 5.0.1_1.1.1, it doesn't start properly due to apparently being unable to access the downloads directory. The directory in question is located on an existing dataset and has a correct ACL entry for UID 568.

When starting 1.1.1, the container remains as "starting" and I'm unable to open a shell to check anything further. The web UI works fine, and reports "Missing Files" for all transfers.

I have not changed any part of the configuration. The save location setting in the web UI is still `/downloads`.

**Comment by alosarjos** [comment]
I'm with the same issue. From this line:

{% set downloads_path = "/downloads" if values.qbittorrent.image_selector == "v4_image" else "/config/Downloads" %}

I see on this repo, it looks like they have changed the storage path from /downloads to /config/Downloads without any kind of message?

**Comment by pealmeid** [comment]
I have the same issue.

**Comment by rrhernandez** [comment]
I have fixed it in the Qbittorrent  Web UI changing "/downloads" to "/config/Downloads", removing pending torrents and uploading .torrent files again.

**Comment by urielsalis** [comment]
On update, it seems like QBittorrent now wants to move all of my downloads from the completed download directory to /downloads/<category name>. Had to rollback to prevent it
