### ISSUE TITLE
qBittorrent 1.1.1 has a permission problem

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/apps#923]
After updating to chart version 1.1.1, qBittorrent stops downloading torrents from the watch folder. Manually adding a torrent via the browser results in:

```2024-11-14 18:48:22.410437+00:00(N) 2024-11-14T19:48:22 - Added new torrent. Torrent: "CENSORED"
2024-11-14 18:48:23.296562+00:00(W) 2024-11-14T19:48:23 - File error alert. Torrent: "CENSORED". File: "/downloads/queue/CENSORED/CENSORED.mp4.!qB". Reason: "CENSORED mkdir (/downloads/queue/CENSORED/CENSORED.mp4.!qB) error: Permission denied"
```

Even though the permissions (`700` with `apps:apps` as owner/group ) have not changed. Reverting back to chart version 1.0.30 fixes the problem: the manually added torrent starts downloading and it immediately picks up torrents from the watch folder.

**Comment by urielsalis** [comment]
Does it sound like https://github.com/truenas/apps/issues/917 ?

**Comment by TimvanDijkNL** [comment]
Not sure if it is the same issue.

Chart version 1.1.2 seems to have fixed this problem. Torrents are picked up from the watch folder and download normally.
