### ISSUE TITLE
[BUG] Scrutiny only scans at container startup

### ISSUE THREAD

**Issue by Eliot-Mess** [truenas/apps#950]
Scrutiny displays scan results only after a container restart. It doesn't update to subsequent scans unless restarted.
I don't know whether it's a display glitch or it fails to show the most recent scan. Although it seems that the temperature graph is updating correctly, and according to Greenwich Mean Time (GMT).

![Screen Shot 2024-11-17 at 16 49 50](https://github.com/user-attachments/assets/c3971393-fbf9-4bd6-8edf-dd767e31d1b1)
![Screen Shot 2024-11-17 at 16 49 03](https://github.com/user-attachments/assets/87d94b55-aeaa-4659-80c6-4c86abaebe4a)

```
Host Disk Path
/dev/sda
Container Disk Path
/dev/sda

Host Disk Path
/dev/sdb
Container Disk Path
/dev/sdb

Host Disk Path
/dev/sdc
Container Disk Path
/dev/sdc

Host Disk Path
/dev/sdd
Container Disk Path
/dev/sdd

Host Disk Path
/dev/sde
Container Disk Path
/dev/sde

Host Disk Path
/dev/sdf
Container Disk Path
/dev/sdf

Host Disk Path
/dev/sdg
Container Disk Path
/dev/sdg
```

Thanks for your time

**Comment by stavros-k** [comment]
I'd suggest checking upstream docs for that. Maybe there is something to set the frequency of that.
If you find somethng that we can set on our end, feel free to let me know!
