### ISSUE TITLE
postgres: requirement of postgres user undocumented & conflict with existing system user

### ISSUE THREAD

**Issue by florianessl** [truenas/apps#955]
**17.1 Installation on TrueNAS 24.10 with a custom host path set for data storage.**
This container immediately stopped every time I tried to set it up, with no indication whatsoever on why. (No logs accessible through GUI?)

I logged into the shell to find the culprit in some well hidden log file:
`initdb: error: could not change permissions of directory \"/var/lib/postgresql/data\": Operation not permitted\n"`

The permissions for my dataset were set to "**apps:apps**" (UNIX ownership) & trying to pass ownership to a newly added user & group named "_postgres_" (as the requirements of the original Dockerfile would indicate) didn't work either.

As it turns out, the user-id has to be **excactly** '999' but this id is already reserved on the host by the system user "_netdata_". So setting the ownership to that one did the trick.

It might be helpful to be able to adjust the user & group on the host & get some better feedback when deployment of a container fails.

**Comment by stavros-k** [comment]
Yes, postgres requires explicit ownership on the data.
Even if it has write access, it will fail if its user is not the owner.

The run-as context metadata card displays the user/group id before and after you install it.

Its just a coincidence that the host has a user account that matches that user/group id.
But container does not know what the host username is, it only cares for specific uid.

User/group on the host is not something that can be adjusted, well it could, but it would be a guacamole game, as each container can use any user-id.
