### ISSUE TITLE
pihole: Update from 1.1.12 to 1.1.14 results in Python error

### ISSUE THREAD

**Issue by NicolasGoeddel** [truenas/apps#969]
Today I tried to upgrade my pihole app but it resulted in an error and I had to roll back.

TrueNAS is up to date:  Current Train: TrueNAS-SCALE-ElectricEel - TrueNAS SCALE ElectricEel 24.10 [release]

Current version of pihole:
![grafik](https://github.com/user-attachments/assets/7350c3b6-da81-491e-89bb-368b1f291eab)

Upgrade dialog:
![grafik](https://github.com/user-attachments/assets/0f59f9d6-4d20-4dc6-a74c-c8c8909e7248)

Failure dialog:
![grafik](https://github.com/user-attachments/assets/dcb6361a-ed06-407a-903c-0cdbecbd0f26)

More info:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/upgrade.py", line 80, in upgrade
    compose_action(
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 57, in compose_action
    raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'pihole' app, please check /var/log/app_lifecycle.log for more details
```

If you need more information please ask.

**Comment by NicolasGoeddel** [comment]
Where can I find that exactly? Do I have to SSH into TrueNAS to get it?

**Comment by stavros-k** [comment]
You should never use an container as a dns server for the host it runs on.
This is a chicken and an egg scenario.

**Comment by stavros-k** [comment]
For future reference, It is mentioned in the error message on your screenshot!

**Comment by NicolasGoeddel** [comment]
Additional info for everyone hitting the same issue:
Just add additional DNS servers like `9.9.9.9`, `1.1.1.1` or anything else to your global network configuration in TrueNAS and it will work fine. You do not need to replace the pihole completely as your first DNS resolver.

**Comment by stavros-k** [comment]
It's still not going to completely solve it. DNS servers are picked randomly. So it won't work always

**Comment by NicolasGoeddel** [comment]
In my case it worked and since TrueNAS seems to just use `/etc/resolv.conf` for DNS resolving it should always use the first one that's reachable. I also does not use `systemd-resolved` so it's just very simple.
Anyway. I think the problem is clear. I have learned my lesson. :smile: Thank you!
