### ISSUE TITLE
How do applications automatically update

### ISSUE THREAD

**Issue by gitbruc** [truenas/apps#974]
why doesn't watchtower work?

**Comment by stavros-k** [comment]
AFAIK watchtower only user the tag defined in the compose file.
I'm not entirely sure, as I don't use it. But based on this premise,

If we have a tag of `1.2.3` it will check in the defined interval to see if there is an "update" tag of `1.2.3`.
But it will not change it to `1.2.4`.

We release update apps every day as long as their tags are picked up by Renovate bot.
if you think there is an app outdated for more then 3 days, feel free to open an issue for it.

**Comment by gitbruc** [comment]
No, I always use the latest version. Watchtower for automatic updates works fine on my other machines, so why doesn't truenas's docker support it? Doesn't TrueNAS have its own method for automatic updates?

**Comment by stavros-k** [comment]
Can you give more details?
Almost none of our apps use latest tag. 
Do you use custom app or prepackaged apps from the catalog?

**Comment by gitbruc** [comment]
![chrome_0CuqdNPcmc](https://github.com/user-attachments/assets/5c83a84b-a781-4ffa-8864-44264f83928a)

Yes,this is my apps.I understand what you mean. Hopefully, there will be an option for automatic updates in the future.
