### ISSUE TITLE
Label Configuration Section - Sometimes there and sometimes not

### ISSUE THREAD

**Issue by Spunky17** [truenas/apps#977]
I've noticed inconsistency with the "Label Configuration" section for apps.  Sometimes the section is present and labels can be added but sometimes it's not.  A good example of this is Plex and Tautulli.  Plex has it and Tautulli does not.  While this does not affect the functionality of the apps but when using other apps like Diun to monitor for new versions and be able to send notifications via web api to tools like Pushover the label section is needed so that Diun can monitor the docker stack for which apps you have configured.

**Comment by stavros-k** [comment]
Its a WIP, every app that is converted to use v2 library gets the label section. It will take a while to convert every app.

See #649

I'll close this issue, mostly because its implemented in the library, just need apps to be upgraded to v2.
Please be patient. 
Thanks!
