### ISSUE TITLE
qBittorrent 1.1.5 resets default save path

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/apps#978]
Issue mentioned in https://github.com/truenas/apps/issues/944# is still present in 1.1.5, despite the issue being closed as completed.

it's not related to the container settings in the TrueNAS apps page, but something in the container itself that seems to reset the setting.

Inside the qBittorrent web UI's settings, I set the download location to `/downloads/completed` but after restarting the docker container it's reset to `/downloads`.

**Comment by stavros-k** [comment]
Please use the field in the edit screen
![Uploading image.png…]()

**Comment by TimvanDijkNL** [comment]
That **is** what I have.. 

![{6268FB96-86E5-4CAC-BB57-76101CAAE2DE}](https://github.com/user-attachments/assets/382c206a-24eb-4a89-8e3c-16033efeb9be)

on that host path I have 2 subfolders `completed` and `queue` which are configured as following inside qBittorrent:

![image](https://github.com/user-attachments/assets/5bcbb9ef-854f-4c23-ab5a-52e60da8d96f)

the option that i have circled is the one that keeps resetting from `/downloads/completed` to `/downloads` after every restart.

**Comment by stavros-k** [comment]
Well in this case there is no way to please every side.
Either qbit or upstream image changed default downloads and made a mess.

I guess I'll revert to not do anything. And users will have to manually fix this.

**Comment by TimvanDijkNL** [comment]
No way to compare the 1.1.1 chart with the 1.1.3 and 1.1.5 charts, to see what caused this ?

**Comment by stavros-k** [comment]
The 1.1.1 did not have the force path set, and it was added to fix users that was getting broken installs on update from previous versions.
The change of the default path was done between qbit v4 and v5.

**Comment by TimvanDijkNL** [comment]
Ahh... gotcha. 

The workaround is to change the setting in the web UI after every restart of the app.. since most people don't restart the apps on a regular basis, I guess it can be lived with. 🤷‍♂️

**Comment by stavros-k** [comment]
I've opened a PR to remove the force path set.
The mount path will still be configurable.
it will be up to the user to define correctly both.

**Comment by Bl00d-B0b** [comment]
qBittorrent does not install at all, even with default settings.

`dashboard
Dashboard
dns
Storage
[Datasets](http://nas0.home.arpa/ui/datasets)
folder_shared
Shares
security
Data Protection
device_hub
Network
vpn_key
Credentials
keyboard_arrow_right
computer
Virtualization
apps
Apps
insert_chart
Reporting
settings
System
keyboard_arrow_right
nas0
TrueNAS SCALE ® © 2024 - [iXsystems, Inc.](https://www.ixsystems.com/)
search
Search UI
Ctrl + /
ApplicationsDiscoverqbittorrent
Install qBittorrent

Application name
Application Name
*
help_outline
[qbittorrent](http://nas0.home.arpa/ui/apps/available/community/qbittorrent)
Version
*
1.1.5

qBittorrent Configuration
Timezone
*
'Europe/Vilnius' timezone
Image Selector
*
help_outline
v5.x.x image.
Additional Environment Variables
No items have been added yet.
Section Help
Configure qBittorrent

User and Group Configuration
User ID
*
help_outline
568
Group ID
*
help_outline
568
Section Help
Configure User and Group for qBittorrent

Network Configuration
WebUI Port
*
help_outline
30024
BT Port
*
help_outline
51413

Use HTTPS Probe
help_outline

Host Network
help_outline
Section Help
Configure Network for qBittorrent

Storage Configuration
qBittorrent Config Storage
help_outline
Type
*
help_outline
ixVolume (Dataset created automatically by the system)
ixVolume Configuration
help_outline

Enable ACL
help_outline
qBittorrent Downloads Storage
help_outline
Mount Path
*
help_outline
/downloads
Type
*
help_outline
ixVolume (Dataset created automatically by the system)
ixVolume Configuration
help_outline

Enable ACL
help_outline
Additional Storage
No items have been added yet.
Section Help
Configure Storage for qBittorrent

Labels Configuration
No items have been added yet.
Section Help
Configure Labels for qBittorrent

Resources Configuration
Limits
CPUs
*
help_outline
2
Memory (in MB)
*
help_outline
4096
Section Help
Configure Resources for qBittorrent
Search Input Fields
Application name
qBittorrent Configuration
User and Group Configuration
Network Configuration
Storage Configuration
Labels Configuration
Resources Configuration
error
FAILED
[EFAULT] Failed 'up' action for 'qbittorrent' app, please check /var/log/app_lifecycle.log for more details
remove_circle_outline
More info...
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 203, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 248, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 241, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 57, in compose_action
    raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'qbittorrent' app, please check /var/log/app_lifecycle.log for more details`
