### ISSUE TITLE
Scrutiny: cap_drop all breaks app

### ISSUE THREAD

**Issue by VladFlorinIlie** [truenas/apps#991]
By dropping all capabilities (besides "SYS_ADMIN" and "SYS_RAWIO"), the app cannot access the internal assets directory from /opt/scrutiny/web/

![image](https://github.com/user-attachments/assets/4db80818-b5f4-4120-a70f-33000d2da90b)

This causes the web page to miss various icons (check the following images):
Working:
![image](https://github.com/user-attachments/assets/3ab711ad-6c4c-4e5b-8f30-66b4181dfa96)

Broken:
![image](https://github.com/user-attachments/assets/57bf404e-bd0b-405e-bd19-831c3ecf829f)

Adding at least the "CAP_DAC_READ_SEARCH" capability fixes it.

**Comment by stavros-k** [comment]
Thanks, weird that there was no logs about these.
